spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/caesar_crawler?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: root
  main:
    banner-mode: off

live:
  record:
    path: /Users/peng.guo/Documents/code/caesar-media/temp/
    ffmpeg-path: ffmpeg
    max-concurrent-records: 10
    max-record-duration: 3600
    reconnect-delay-max: 5
    rw-timeout: 10000000
    buffer-size: 8192
    auto-cleanup: true
    retention-days: 7
