// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

// Protobuf Java Version: 3.25.5
package org.caesar.crawler.live.douyin.codec.protobuf;

public interface ChatMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ChatMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Common common = 1;</code>
   * @return Whether the common field is set.
   */
  boolean hasCommon();
  /**
   * <code>.Common common = 1;</code>
   * @return The common.
   */
  org.caesar.crawler.live.douyin.codec.protobuf.Common getCommon();
  /**
   * <code>.Common common = 1;</code>
   */
  org.caesar.crawler.live.douyin.codec.protobuf.CommonOrBuilder getCommonOrBuilder();

  /**
   * <code>.User user = 2;</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <code>.User user = 2;</code>
   * @return The user.
   */
  org.caesar.crawler.live.douyin.codec.protobuf.User getUser();
  /**
   * <code>.User user = 2;</code>
   */
  org.caesar.crawler.live.douyin.codec.protobuf.UserOrBuilder getUserOrBuilder();

  /**
   * <code>string content = 3;</code>
   * @return The content.
   */
  String getContent();
  /**
   * <code>string content = 3;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>bool visibleToSender = 4;</code>
   * @return The visibleToSender.
   */
  boolean getVisibleToSender();

  /**
   * <code>.Image backgroundImage = 5;</code>
   * @return Whether the backgroundImage field is set.
   */
  boolean hasBackgroundImage();
  /**
   * <code>.Image backgroundImage = 5;</code>
   * @return The backgroundImage.
   */
  org.caesar.crawler.live.douyin.codec.protobuf.Image getBackgroundImage();
  /**
   * <code>.Image backgroundImage = 5;</code>
   */
  org.caesar.crawler.live.douyin.codec.protobuf.ImageOrBuilder getBackgroundImageOrBuilder();

  /**
   * <code>string fullScreenTextColor = 6;</code>
   * @return The fullScreenTextColor.
   */
  String getFullScreenTextColor();
  /**
   * <code>string fullScreenTextColor = 6;</code>
   * @return The bytes for fullScreenTextColor.
   */
  com.google.protobuf.ByteString
      getFullScreenTextColorBytes();

  /**
   * <code>.Image backgroundImageV2 = 7;</code>
   * @return Whether the backgroundImageV2 field is set.
   */
  boolean hasBackgroundImageV2();
  /**
   * <code>.Image backgroundImageV2 = 7;</code>
   * @return The backgroundImageV2.
   */
  org.caesar.crawler.live.douyin.codec.protobuf.Image getBackgroundImageV2();
  /**
   * <code>.Image backgroundImageV2 = 7;</code>
   */
  org.caesar.crawler.live.douyin.codec.protobuf.ImageOrBuilder getBackgroundImageV2OrBuilder();

  /**
   * <code>.PublicAreaCommon publicAreaCommon = 9;</code>
   * @return Whether the publicAreaCommon field is set.
   */
  boolean hasPublicAreaCommon();
  /**
   * <code>.PublicAreaCommon publicAreaCommon = 9;</code>
   * @return The publicAreaCommon.
   */
  org.caesar.crawler.live.douyin.codec.protobuf.PublicAreaCommon getPublicAreaCommon();
  /**
   * <code>.PublicAreaCommon publicAreaCommon = 9;</code>
   */
  org.caesar.crawler.live.douyin.codec.protobuf.PublicAreaCommonOrBuilder getPublicAreaCommonOrBuilder();

  /**
   * <code>.Image giftImage = 10;</code>
   * @return Whether the giftImage field is set.
   */
  boolean hasGiftImage();
  /**
   * <code>.Image giftImage = 10;</code>
   * @return The giftImage.
   */
  org.caesar.crawler.live.douyin.codec.protobuf.Image getGiftImage();
  /**
   * <code>.Image giftImage = 10;</code>
   */
  org.caesar.crawler.live.douyin.codec.protobuf.ImageOrBuilder getGiftImageOrBuilder();

  /**
   * <code>uint64 agreeMsgId = 11;</code>
   * @return The agreeMsgId.
   */
  long getAgreeMsgId();

  /**
   * <code>uint32 priorityLevel = 12;</code>
   * @return The priorityLevel.
   */
  int getPriorityLevel();

  /**
   * <code>.LandscapeAreaCommon landscapeAreaCommon = 13;</code>
   * @return Whether the landscapeAreaCommon field is set.
   */
  boolean hasLandscapeAreaCommon();
  /**
   * <code>.LandscapeAreaCommon landscapeAreaCommon = 13;</code>
   * @return The landscapeAreaCommon.
   */
  org.caesar.crawler.live.douyin.codec.protobuf.LandscapeAreaCommon getLandscapeAreaCommon();
  /**
   * <code>.LandscapeAreaCommon landscapeAreaCommon = 13;</code>
   */
  org.caesar.crawler.live.douyin.codec.protobuf.LandscapeAreaCommonOrBuilder getLandscapeAreaCommonOrBuilder();

  /**
   * <code>uint64 eventTime = 15;</code>
   * @return The eventTime.
   */
  long getEventTime();

  /**
   * <code>bool sendReview = 16;</code>
   * @return The sendReview.
   */
  boolean getSendReview();

  /**
   * <code>bool fromIntercom = 17;</code>
   * @return The fromIntercom.
   */
  boolean getFromIntercom();

  /**
   * <code>bool intercomHideUserCard = 18;</code>
   * @return The intercomHideUserCard.
   */
  boolean getIntercomHideUserCard();

  /**
   * <pre>
   *  repeated chatTagsList = 19;
   * </pre>
   *
   * <code>string chatBy = 20;</code>
   * @return The chatBy.
   */
  String getChatBy();
  /**
   * <pre>
   *  repeated chatTagsList = 19;
   * </pre>
   *
   * <code>string chatBy = 20;</code>
   * @return The bytes for chatBy.
   */
  com.google.protobuf.ByteString
      getChatByBytes();

  /**
   * <code>uint32 individualChatPriority = 21;</code>
   * @return The individualChatPriority.
   */
  int getIndividualChatPriority();

  /**
   * <code>.Text rtfContent = 22;</code>
   * @return Whether the rtfContent field is set.
   */
  boolean hasRtfContent();
  /**
   * <code>.Text rtfContent = 22;</code>
   * @return The rtfContent.
   */
  org.caesar.crawler.live.douyin.codec.protobuf.Text getRtfContent();
  /**
   * <code>.Text rtfContent = 22;</code>
   */
  org.caesar.crawler.live.douyin.codec.protobuf.TextOrBuilder getRtfContentOrBuilder();
}
