// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

// Protobuf Java Version: 3.25.5
package org.caesar.crawler.live.douyin.codec.protobuf;

public interface ControlMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ControlMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Common common = 1;</code>
   * @return Whether the common field is set.
   */
  boolean hasCommon();
  /**
   * <code>.Common common = 1;</code>
   * @return The common.
   */
  org.caesar.crawler.live.douyin.codec.protobuf.Common getCommon();
  /**
   * <code>.Common common = 1;</code>
   */
  org.caesar.crawler.live.douyin.codec.protobuf.CommonOrBuilder getCommonOrBuilder();

  /**
   * <code>int32 status = 2;</code>
   * @return The status.
   */
  int getStatus();
}
