// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

// Protobuf Java Version: 3.25.5
package org.caesar.crawler.live.douyin.codec.protobuf;

public interface GradeBuffInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GradeBuffInfo)
    com.google.protobuf.MessageOrBuilder {
}
