// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

// Protobuf Java Version: 3.25.5
package org.caesar.crawler.live.douyin.codec.protobuf;

public interface ImageContentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ImageContent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string fontColor = 2;</code>
   * @return The fontColor.
   */
  String getFontColor();
  /**
   * <code>string fontColor = 2;</code>
   * @return The bytes for fontColor.
   */
  com.google.protobuf.ByteString
      getFontColorBytes();

  /**
   * <code>uint64 level = 3;</code>
   * @return The level.
   */
  long getLevel();

  /**
   * <code>string alternativeText = 4;</code>
   * @return The alternativeText.
   */
  String getAlternativeText();
  /**
   * <code>string alternativeText = 4;</code>
   * @return The bytes for alternativeText.
   */
  com.google.protobuf.ByteString
      getAlternativeTextBytes();
}
