// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

// Protobuf Java Version: 3.25.5
package org.caesar.crawler.live.douyin.codec.protobuf;

/**
 * Protobuf type {@code InRoomBannerMessage}
 */
public final class InRoomBannerMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:InRoomBannerMessage)
    InRoomBannerMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use InRoomBannerMessage.newBuilder() to construct.
  private InRoomBannerMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InRoomBannerMessage() {
    extra_ = "";
    containerUrl_ = "";
    lynxContainerUrl_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new InRoomBannerMessage();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.caesar.crawler.live.douyin.codec.protobuf.Douyin.internal_static_InRoomBannerMessage_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.caesar.crawler.live.douyin.codec.protobuf.Douyin.internal_static_InRoomBannerMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.caesar.crawler.live.douyin.codec.protobuf.InRoomBannerMessage.class, org.caesar.crawler.live.douyin.codec.protobuf.InRoomBannerMessage.Builder.class);
  }

  private int bitField0_;
  public static final int COMMON_FIELD_NUMBER = 1;
  private org.caesar.crawler.live.douyin.codec.protobuf.Common common_;
  /**
   * <pre>
   * common 字段，引用 Common 消息类型
   * </pre>
   *
   * <code>.Common common = 1;</code>
   * @return Whether the common field is set.
   */
  @Override
  public boolean hasCommon() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * common 字段，引用 Common 消息类型
   * </pre>
   *
   * <code>.Common common = 1;</code>
   * @return The common.
   */
  @Override
  public org.caesar.crawler.live.douyin.codec.protobuf.Common getCommon() {
    return common_ == null ? org.caesar.crawler.live.douyin.codec.protobuf.Common.getDefaultInstance() : common_;
  }
  /**
   * <pre>
   * common 字段，引用 Common 消息类型
   * </pre>
   *
   * <code>.Common common = 1;</code>
   */
  @Override
  public org.caesar.crawler.live.douyin.codec.protobuf.CommonOrBuilder getCommonOrBuilder() {
    return common_ == null ? org.caesar.crawler.live.douyin.codec.protobuf.Common.getDefaultInstance() : common_;
  }

  public static final int EXTRA_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile Object extra_ = "";
  /**
   * <pre>
   * extra 字段，字符串类型
   * </pre>
   *
   * <code>string extra = 2;</code>
   * @return The extra.
   */
  @Override
  public String getExtra() {
    Object ref = extra_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      extra_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * extra 字段，字符串类型
   * </pre>
   *
   * <code>string extra = 2;</code>
   * @return The bytes for extra.
   */
  @Override
  public com.google.protobuf.ByteString
      getExtraBytes() {
    Object ref = extra_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      extra_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int POSITION_FIELD_NUMBER = 3;
  private int position_ = 0;
  /**
   * <pre>
   * position 字段，整型
   * </pre>
   *
   * <code>int32 position = 3;</code>
   * @return The position.
   */
  @Override
  public int getPosition() {
    return position_;
  }

  public static final int ACTION_TYPE_FIELD_NUMBER = 4;
  private int actionType_ = 0;
  /**
   * <pre>
   * action_type 字段，整型
   * </pre>
   *
   * <code>int32 action_type = 4;</code>
   * @return The actionType.
   */
  @Override
  public int getActionType() {
    return actionType_;
  }

  public static final int CONTAINER_URL_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile Object containerUrl_ = "";
  /**
   * <pre>
   * container_url 字段，字符串类型
   * </pre>
   *
   * <code>string container_url = 5;</code>
   * @return The containerUrl.
   */
  @Override
  public String getContainerUrl() {
    Object ref = containerUrl_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      containerUrl_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * container_url 字段，字符串类型
   * </pre>
   *
   * <code>string container_url = 5;</code>
   * @return The bytes for containerUrl.
   */
  @Override
  public com.google.protobuf.ByteString
      getContainerUrlBytes() {
    Object ref = containerUrl_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      containerUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LYNX_CONTAINER_URL_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile Object lynxContainerUrl_ = "";
  /**
   * <pre>
   * lynx_container_url 字段，字符串类型
   * </pre>
   *
   * <code>string lynx_container_url = 6;</code>
   * @return The lynxContainerUrl.
   */
  @Override
  public String getLynxContainerUrl() {
    Object ref = lynxContainerUrl_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      lynxContainerUrl_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * lynx_container_url 字段，字符串类型
   * </pre>
   *
   * <code>string lynx_container_url = 6;</code>
   * @return The bytes for lynxContainerUrl.
   */
  @Override
  public com.google.protobuf.ByteString
      getLynxContainerUrlBytes() {
    Object ref = lynxContainerUrl_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      lynxContainerUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTAINER_TYPE_FIELD_NUMBER = 7;
  private int containerType_ = 0;
  /**
   * <pre>
   * container_type 字段，整型
   * </pre>
   *
   * <code>int32 container_type = 7;</code>
   * @return The containerType.
   */
  @Override
  public int getContainerType() {
    return containerType_;
  }

  public static final int OP_TYPE_FIELD_NUMBER = 8;
  private int opType_ = 0;
  /**
   * <pre>
   * op_type 字段，整型
   * </pre>
   *
   * <code>int32 op_type = 8;</code>
   * @return The opType.
   */
  @Override
  public int getOpType() {
    return opType_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getCommon());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(extra_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, extra_);
    }
    if (position_ != 0) {
      output.writeInt32(3, position_);
    }
    if (actionType_ != 0) {
      output.writeInt32(4, actionType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(containerUrl_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, containerUrl_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lynxContainerUrl_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, lynxContainerUrl_);
    }
    if (containerType_ != 0) {
      output.writeInt32(7, containerType_);
    }
    if (opType_ != 0) {
      output.writeInt32(8, opType_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getCommon());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(extra_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, extra_);
    }
    if (position_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, position_);
    }
    if (actionType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, actionType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(containerUrl_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, containerUrl_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lynxContainerUrl_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, lynxContainerUrl_);
    }
    if (containerType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, containerType_);
    }
    if (opType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, opType_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.caesar.crawler.live.douyin.codec.protobuf.InRoomBannerMessage)) {
      return super.equals(obj);
    }
    org.caesar.crawler.live.douyin.codec.protobuf.InRoomBannerMessage other = (org.caesar.crawler.live.douyin.codec.protobuf.InRoomBannerMessage) obj;

    if (hasCommon() != other.hasCommon()) return false;
    if (hasCommon()) {
      if (!getCommon()
          .equals(other.getCommon())) return false;
    }
    if (!getExtra()
        .equals(other.getExtra())) return false;
    if (getPosition()
        != other.getPosition()) return false;
    if (getActionType()
        != other.getActionType()) return false;
    if (!getContainerUrl()
        .equals(other.getContainerUrl())) return false;
    if (!getLynxContainerUrl()
        .equals(other.getLynxContainerUrl())) return false;
    if (getContainerType()
        != other.getContainerType()) return false;
    if (getOpType()
        != other.getOpType()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCommon()) {
      hash = (37 * hash) + COMMON_FIELD_NUMBER;
      hash = (53 * hash) + getCommon().hashCode();
    }
    hash = (37 * hash) + EXTRA_FIELD_NUMBER;
    hash = (53 * hash) + getExtra().hashCode();
    hash = (37 * hash) + POSITION_FIELD_NUMBER;
    hash = (53 * hash) + getPosition();
    hash = (37 * hash) + ACTION_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getActionType();
    hash = (37 * hash) + CONTAINER_URL_FIELD_NUMBER;
    hash = (53 * hash) + getContainerUrl().hashCode();
    hash = (37 * hash) + LYNX_CONTAINER_URL_FIELD_NUMBER;
    hash = (53 * hash) + getLynxContainerUrl().hashCode();
    hash = (37 * hash) + CONTAINER_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getContainerType();
    hash = (37 * hash) + OP_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getOpType();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.caesar.crawler.live.douyin.codec.protobuf.InRoomBannerMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.caesar.crawler.live.douyin.codec.protobuf.InRoomBannerMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.caesar.crawler.live.douyin.codec.protobuf.InRoomBannerMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.caesar.crawler.live.douyin.codec.protobuf.InRoomBannerMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.caesar.crawler.live.douyin.codec.protobuf.InRoomBannerMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.caesar.crawler.live.douyin.codec.protobuf.InRoomBannerMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.caesar.crawler.live.douyin.codec.protobuf.InRoomBannerMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.caesar.crawler.live.douyin.codec.protobuf.InRoomBannerMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.caesar.crawler.live.douyin.codec.protobuf.InRoomBannerMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.caesar.crawler.live.douyin.codec.protobuf.InRoomBannerMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.caesar.crawler.live.douyin.codec.protobuf.InRoomBannerMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.caesar.crawler.live.douyin.codec.protobuf.InRoomBannerMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.caesar.crawler.live.douyin.codec.protobuf.InRoomBannerMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code InRoomBannerMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:InRoomBannerMessage)
      org.caesar.crawler.live.douyin.codec.protobuf.InRoomBannerMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.caesar.crawler.live.douyin.codec.protobuf.Douyin.internal_static_InRoomBannerMessage_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.caesar.crawler.live.douyin.codec.protobuf.Douyin.internal_static_InRoomBannerMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.caesar.crawler.live.douyin.codec.protobuf.InRoomBannerMessage.class, org.caesar.crawler.live.douyin.codec.protobuf.InRoomBannerMessage.Builder.class);
    }

    // Construct using org.caesar.crawler.live.douyin.codec.protobuf.InRoomBannerMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCommonFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      common_ = null;
      if (commonBuilder_ != null) {
        commonBuilder_.dispose();
        commonBuilder_ = null;
      }
      extra_ = "";
      position_ = 0;
      actionType_ = 0;
      containerUrl_ = "";
      lynxContainerUrl_ = "";
      containerType_ = 0;
      opType_ = 0;
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.caesar.crawler.live.douyin.codec.protobuf.Douyin.internal_static_InRoomBannerMessage_descriptor;
    }

    @Override
    public org.caesar.crawler.live.douyin.codec.protobuf.InRoomBannerMessage getDefaultInstanceForType() {
      return org.caesar.crawler.live.douyin.codec.protobuf.InRoomBannerMessage.getDefaultInstance();
    }

    @Override
    public org.caesar.crawler.live.douyin.codec.protobuf.InRoomBannerMessage build() {
      org.caesar.crawler.live.douyin.codec.protobuf.InRoomBannerMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public org.caesar.crawler.live.douyin.codec.protobuf.InRoomBannerMessage buildPartial() {
      org.caesar.crawler.live.douyin.codec.protobuf.InRoomBannerMessage result = new org.caesar.crawler.live.douyin.codec.protobuf.InRoomBannerMessage(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.caesar.crawler.live.douyin.codec.protobuf.InRoomBannerMessage result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.common_ = commonBuilder_ == null
            ? common_
            : commonBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.extra_ = extra_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.position_ = position_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.actionType_ = actionType_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.containerUrl_ = containerUrl_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.lynxContainerUrl_ = lynxContainerUrl_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.containerType_ = containerType_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.opType_ = opType_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.caesar.crawler.live.douyin.codec.protobuf.InRoomBannerMessage) {
        return mergeFrom((org.caesar.crawler.live.douyin.codec.protobuf.InRoomBannerMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.caesar.crawler.live.douyin.codec.protobuf.InRoomBannerMessage other) {
      if (other == org.caesar.crawler.live.douyin.codec.protobuf.InRoomBannerMessage.getDefaultInstance()) return this;
      if (other.hasCommon()) {
        mergeCommon(other.getCommon());
      }
      if (!other.getExtra().isEmpty()) {
        extra_ = other.extra_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getPosition() != 0) {
        setPosition(other.getPosition());
      }
      if (other.getActionType() != 0) {
        setActionType(other.getActionType());
      }
      if (!other.getContainerUrl().isEmpty()) {
        containerUrl_ = other.containerUrl_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getLynxContainerUrl().isEmpty()) {
        lynxContainerUrl_ = other.lynxContainerUrl_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (other.getContainerType() != 0) {
        setContainerType(other.getContainerType());
      }
      if (other.getOpType() != 0) {
        setOpType(other.getOpType());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getCommonFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              extra_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              position_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              actionType_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              containerUrl_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              lynxContainerUrl_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 56: {
              containerType_ = input.readInt32();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              opType_ = input.readInt32();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private org.caesar.crawler.live.douyin.codec.protobuf.Common common_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.caesar.crawler.live.douyin.codec.protobuf.Common, org.caesar.crawler.live.douyin.codec.protobuf.Common.Builder, org.caesar.crawler.live.douyin.codec.protobuf.CommonOrBuilder> commonBuilder_;
    /**
     * <pre>
     * common 字段，引用 Common 消息类型
     * </pre>
     *
     * <code>.Common common = 1;</code>
     * @return Whether the common field is set.
     */
    public boolean hasCommon() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * common 字段，引用 Common 消息类型
     * </pre>
     *
     * <code>.Common common = 1;</code>
     * @return The common.
     */
    public org.caesar.crawler.live.douyin.codec.protobuf.Common getCommon() {
      if (commonBuilder_ == null) {
        return common_ == null ? org.caesar.crawler.live.douyin.codec.protobuf.Common.getDefaultInstance() : common_;
      } else {
        return commonBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * common 字段，引用 Common 消息类型
     * </pre>
     *
     * <code>.Common common = 1;</code>
     */
    public Builder setCommon(org.caesar.crawler.live.douyin.codec.protobuf.Common value) {
      if (commonBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        common_ = value;
      } else {
        commonBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * common 字段，引用 Common 消息类型
     * </pre>
     *
     * <code>.Common common = 1;</code>
     */
    public Builder setCommon(
        org.caesar.crawler.live.douyin.codec.protobuf.Common.Builder builderForValue) {
      if (commonBuilder_ == null) {
        common_ = builderForValue.build();
      } else {
        commonBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * common 字段，引用 Common 消息类型
     * </pre>
     *
     * <code>.Common common = 1;</code>
     */
    public Builder mergeCommon(org.caesar.crawler.live.douyin.codec.protobuf.Common value) {
      if (commonBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          common_ != null &&
          common_ != org.caesar.crawler.live.douyin.codec.protobuf.Common.getDefaultInstance()) {
          getCommonBuilder().mergeFrom(value);
        } else {
          common_ = value;
        }
      } else {
        commonBuilder_.mergeFrom(value);
      }
      if (common_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * common 字段，引用 Common 消息类型
     * </pre>
     *
     * <code>.Common common = 1;</code>
     */
    public Builder clearCommon() {
      bitField0_ = (bitField0_ & ~0x00000001);
      common_ = null;
      if (commonBuilder_ != null) {
        commonBuilder_.dispose();
        commonBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * common 字段，引用 Common 消息类型
     * </pre>
     *
     * <code>.Common common = 1;</code>
     */
    public org.caesar.crawler.live.douyin.codec.protobuf.Common.Builder getCommonBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getCommonFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * common 字段，引用 Common 消息类型
     * </pre>
     *
     * <code>.Common common = 1;</code>
     */
    public org.caesar.crawler.live.douyin.codec.protobuf.CommonOrBuilder getCommonOrBuilder() {
      if (commonBuilder_ != null) {
        return commonBuilder_.getMessageOrBuilder();
      } else {
        return common_ == null ?
            org.caesar.crawler.live.douyin.codec.protobuf.Common.getDefaultInstance() : common_;
      }
    }
    /**
     * <pre>
     * common 字段，引用 Common 消息类型
     * </pre>
     *
     * <code>.Common common = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.caesar.crawler.live.douyin.codec.protobuf.Common, org.caesar.crawler.live.douyin.codec.protobuf.Common.Builder, org.caesar.crawler.live.douyin.codec.protobuf.CommonOrBuilder>
        getCommonFieldBuilder() {
      if (commonBuilder_ == null) {
        commonBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.caesar.crawler.live.douyin.codec.protobuf.Common, org.caesar.crawler.live.douyin.codec.protobuf.Common.Builder, org.caesar.crawler.live.douyin.codec.protobuf.CommonOrBuilder>(
                getCommon(),
                getParentForChildren(),
                isClean());
        common_ = null;
      }
      return commonBuilder_;
    }

    private Object extra_ = "";
    /**
     * <pre>
     * extra 字段，字符串类型
     * </pre>
     *
     * <code>string extra = 2;</code>
     * @return The extra.
     */
    public String getExtra() {
      Object ref = extra_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        extra_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * extra 字段，字符串类型
     * </pre>
     *
     * <code>string extra = 2;</code>
     * @return The bytes for extra.
     */
    public com.google.protobuf.ByteString
        getExtraBytes() {
      Object ref = extra_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        extra_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * extra 字段，字符串类型
     * </pre>
     *
     * <code>string extra = 2;</code>
     * @param value The extra to set.
     * @return This builder for chaining.
     */
    public Builder setExtra(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      extra_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * extra 字段，字符串类型
     * </pre>
     *
     * <code>string extra = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearExtra() {
      extra_ = getDefaultInstance().getExtra();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * extra 字段，字符串类型
     * </pre>
     *
     * <code>string extra = 2;</code>
     * @param value The bytes for extra to set.
     * @return This builder for chaining.
     */
    public Builder setExtraBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      extra_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int position_ ;
    /**
     * <pre>
     * position 字段，整型
     * </pre>
     *
     * <code>int32 position = 3;</code>
     * @return The position.
     */
    @Override
    public int getPosition() {
      return position_;
    }
    /**
     * <pre>
     * position 字段，整型
     * </pre>
     *
     * <code>int32 position = 3;</code>
     * @param value The position to set.
     * @return This builder for chaining.
     */
    public Builder setPosition(int value) {

      position_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * position 字段，整型
     * </pre>
     *
     * <code>int32 position = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPosition() {
      bitField0_ = (bitField0_ & ~0x00000004);
      position_ = 0;
      onChanged();
      return this;
    }

    private int actionType_ ;
    /**
     * <pre>
     * action_type 字段，整型
     * </pre>
     *
     * <code>int32 action_type = 4;</code>
     * @return The actionType.
     */
    @Override
    public int getActionType() {
      return actionType_;
    }
    /**
     * <pre>
     * action_type 字段，整型
     * </pre>
     *
     * <code>int32 action_type = 4;</code>
     * @param value The actionType to set.
     * @return This builder for chaining.
     */
    public Builder setActionType(int value) {

      actionType_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * action_type 字段，整型
     * </pre>
     *
     * <code>int32 action_type = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearActionType() {
      bitField0_ = (bitField0_ & ~0x00000008);
      actionType_ = 0;
      onChanged();
      return this;
    }

    private Object containerUrl_ = "";
    /**
     * <pre>
     * container_url 字段，字符串类型
     * </pre>
     *
     * <code>string container_url = 5;</code>
     * @return The containerUrl.
     */
    public String getContainerUrl() {
      Object ref = containerUrl_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        containerUrl_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * container_url 字段，字符串类型
     * </pre>
     *
     * <code>string container_url = 5;</code>
     * @return The bytes for containerUrl.
     */
    public com.google.protobuf.ByteString
        getContainerUrlBytes() {
      Object ref = containerUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        containerUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * container_url 字段，字符串类型
     * </pre>
     *
     * <code>string container_url = 5;</code>
     * @param value The containerUrl to set.
     * @return This builder for chaining.
     */
    public Builder setContainerUrl(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      containerUrl_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * container_url 字段，字符串类型
     * </pre>
     *
     * <code>string container_url = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearContainerUrl() {
      containerUrl_ = getDefaultInstance().getContainerUrl();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * container_url 字段，字符串类型
     * </pre>
     *
     * <code>string container_url = 5;</code>
     * @param value The bytes for containerUrl to set.
     * @return This builder for chaining.
     */
    public Builder setContainerUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      containerUrl_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private Object lynxContainerUrl_ = "";
    /**
     * <pre>
     * lynx_container_url 字段，字符串类型
     * </pre>
     *
     * <code>string lynx_container_url = 6;</code>
     * @return The lynxContainerUrl.
     */
    public String getLynxContainerUrl() {
      Object ref = lynxContainerUrl_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        lynxContainerUrl_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * lynx_container_url 字段，字符串类型
     * </pre>
     *
     * <code>string lynx_container_url = 6;</code>
     * @return The bytes for lynxContainerUrl.
     */
    public com.google.protobuf.ByteString
        getLynxContainerUrlBytes() {
      Object ref = lynxContainerUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        lynxContainerUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * lynx_container_url 字段，字符串类型
     * </pre>
     *
     * <code>string lynx_container_url = 6;</code>
     * @param value The lynxContainerUrl to set.
     * @return This builder for chaining.
     */
    public Builder setLynxContainerUrl(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      lynxContainerUrl_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * lynx_container_url 字段，字符串类型
     * </pre>
     *
     * <code>string lynx_container_url = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearLynxContainerUrl() {
      lynxContainerUrl_ = getDefaultInstance().getLynxContainerUrl();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * lynx_container_url 字段，字符串类型
     * </pre>
     *
     * <code>string lynx_container_url = 6;</code>
     * @param value The bytes for lynxContainerUrl to set.
     * @return This builder for chaining.
     */
    public Builder setLynxContainerUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      lynxContainerUrl_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private int containerType_ ;
    /**
     * <pre>
     * container_type 字段，整型
     * </pre>
     *
     * <code>int32 container_type = 7;</code>
     * @return The containerType.
     */
    @Override
    public int getContainerType() {
      return containerType_;
    }
    /**
     * <pre>
     * container_type 字段，整型
     * </pre>
     *
     * <code>int32 container_type = 7;</code>
     * @param value The containerType to set.
     * @return This builder for chaining.
     */
    public Builder setContainerType(int value) {

      containerType_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * container_type 字段，整型
     * </pre>
     *
     * <code>int32 container_type = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearContainerType() {
      bitField0_ = (bitField0_ & ~0x00000040);
      containerType_ = 0;
      onChanged();
      return this;
    }

    private int opType_ ;
    /**
     * <pre>
     * op_type 字段，整型
     * </pre>
     *
     * <code>int32 op_type = 8;</code>
     * @return The opType.
     */
    @Override
    public int getOpType() {
      return opType_;
    }
    /**
     * <pre>
     * op_type 字段，整型
     * </pre>
     *
     * <code>int32 op_type = 8;</code>
     * @param value The opType to set.
     * @return This builder for chaining.
     */
    public Builder setOpType(int value) {

      opType_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * op_type 字段，整型
     * </pre>
     *
     * <code>int32 op_type = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearOpType() {
      bitField0_ = (bitField0_ & ~0x00000080);
      opType_ = 0;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:InRoomBannerMessage)
  }

  // @@protoc_insertion_point(class_scope:InRoomBannerMessage)
  private static final org.caesar.crawler.live.douyin.codec.protobuf.InRoomBannerMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.caesar.crawler.live.douyin.codec.protobuf.InRoomBannerMessage();
  }

  public static org.caesar.crawler.live.douyin.codec.protobuf.InRoomBannerMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InRoomBannerMessage>
      PARSER = new com.google.protobuf.AbstractParser<InRoomBannerMessage>() {
    @Override
    public InRoomBannerMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<InRoomBannerMessage> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<InRoomBannerMessage> getParserForType() {
    return PARSER;
  }

  @Override
  public org.caesar.crawler.live.douyin.codec.protobuf.InRoomBannerMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

