// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

// Protobuf Java Version: 3.25.5
package org.caesar.crawler.live.douyin.codec.protobuf;

/**
 * Protobuf type {@code LandscapeAreaCommon}
 */
public final class LandscapeAreaCommon extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:LandscapeAreaCommon)
    LandscapeAreaCommonOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LandscapeAreaCommon.newBuilder() to construct.
  private LandscapeAreaCommon(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LandscapeAreaCommon() {
    colorValueList_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    commentTypeTagsList_ = java.util.Collections.emptyList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new LandscapeAreaCommon();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.caesar.crawler.live.douyin.codec.protobuf.Douyin.internal_static_LandscapeAreaCommon_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.caesar.crawler.live.douyin.codec.protobuf.Douyin.internal_static_LandscapeAreaCommon_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.caesar.crawler.live.douyin.codec.protobuf.LandscapeAreaCommon.class, org.caesar.crawler.live.douyin.codec.protobuf.LandscapeAreaCommon.Builder.class);
  }

  public static final int SHOWHEAD_FIELD_NUMBER = 1;
  private boolean showHead_ = false;
  /**
   * <code>bool showHead = 1;</code>
   * @return The showHead.
   */
  @Override
  public boolean getShowHead() {
    return showHead_;
  }

  public static final int SHOWNICKNAME_FIELD_NUMBER = 2;
  private boolean showNickname_ = false;
  /**
   * <code>bool showNickname = 2;</code>
   * @return The showNickname.
   */
  @Override
  public boolean getShowNickname() {
    return showNickname_;
  }

  public static final int SHOWFONTCOLOR_FIELD_NUMBER = 3;
  private boolean showFontColor_ = false;
  /**
   * <code>bool showFontColor = 3;</code>
   * @return The showFontColor.
   */
  @Override
  public boolean getShowFontColor() {
    return showFontColor_;
  }

  public static final int COLORVALUELIST_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList colorValueList_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string colorValueList = 4;</code>
   * @return A list containing the colorValueList.
   */
  public com.google.protobuf.ProtocolStringList
      getColorValueListList() {
    return colorValueList_;
  }
  /**
   * <code>repeated string colorValueList = 4;</code>
   * @return The count of colorValueList.
   */
  public int getColorValueListCount() {
    return colorValueList_.size();
  }
  /**
   * <code>repeated string colorValueList = 4;</code>
   * @param index The index of the element to return.
   * @return The colorValueList at the given index.
   */
  public String getColorValueList(int index) {
    return colorValueList_.get(index);
  }
  /**
   * <code>repeated string colorValueList = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the colorValueList at the given index.
   */
  public com.google.protobuf.ByteString
      getColorValueListBytes(int index) {
    return colorValueList_.getByteString(index);
  }

  public static final int COMMENTTYPETAGSLIST_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private java.util.List<Integer> commentTypeTagsList_;
  private static final com.google.protobuf.Internal.ListAdapter.Converter<
      Integer, org.caesar.crawler.live.douyin.codec.protobuf.CommentTypeTag> commentTypeTagsList_converter_ =
          new com.google.protobuf.Internal.ListAdapter.Converter<
              Integer, org.caesar.crawler.live.douyin.codec.protobuf.CommentTypeTag>() {
            public org.caesar.crawler.live.douyin.codec.protobuf.CommentTypeTag convert(Integer from) {
              org.caesar.crawler.live.douyin.codec.protobuf.CommentTypeTag result = org.caesar.crawler.live.douyin.codec.protobuf.CommentTypeTag.forNumber(from);
              return result == null ? org.caesar.crawler.live.douyin.codec.protobuf.CommentTypeTag.UNRECOGNIZED : result;
            }
          };
  /**
   * <code>repeated .CommentTypeTag commentTypeTagsList = 5;</code>
   * @return A list containing the commentTypeTagsList.
   */
  @Override
  public java.util.List<org.caesar.crawler.live.douyin.codec.protobuf.CommentTypeTag> getCommentTypeTagsListList() {
    return new com.google.protobuf.Internal.ListAdapter<
        Integer, org.caesar.crawler.live.douyin.codec.protobuf.CommentTypeTag>(commentTypeTagsList_, commentTypeTagsList_converter_);
  }
  /**
   * <code>repeated .CommentTypeTag commentTypeTagsList = 5;</code>
   * @return The count of commentTypeTagsList.
   */
  @Override
  public int getCommentTypeTagsListCount() {
    return commentTypeTagsList_.size();
  }
  /**
   * <code>repeated .CommentTypeTag commentTypeTagsList = 5;</code>
   * @param index The index of the element to return.
   * @return The commentTypeTagsList at the given index.
   */
  @Override
  public org.caesar.crawler.live.douyin.codec.protobuf.CommentTypeTag getCommentTypeTagsList(int index) {
    return commentTypeTagsList_converter_.convert(commentTypeTagsList_.get(index));
  }
  /**
   * <code>repeated .CommentTypeTag commentTypeTagsList = 5;</code>
   * @return A list containing the enum numeric values on the wire for commentTypeTagsList.
   */
  @Override
  public java.util.List<Integer>
  getCommentTypeTagsListValueList() {
    return commentTypeTagsList_;
  }
  /**
   * <code>repeated .CommentTypeTag commentTypeTagsList = 5;</code>
   * @param index The index of the value to return.
   * @return The enum numeric value on the wire of commentTypeTagsList at the given index.
   */
  @Override
  public int getCommentTypeTagsListValue(int index) {
    return commentTypeTagsList_.get(index);
  }
  private int commentTypeTagsListMemoizedSerializedSize;

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (showHead_ != false) {
      output.writeBool(1, showHead_);
    }
    if (showNickname_ != false) {
      output.writeBool(2, showNickname_);
    }
    if (showFontColor_ != false) {
      output.writeBool(3, showFontColor_);
    }
    for (int i = 0; i < colorValueList_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, colorValueList_.getRaw(i));
    }
    if (getCommentTypeTagsListList().size() > 0) {
      output.writeUInt32NoTag(42);
      output.writeUInt32NoTag(commentTypeTagsListMemoizedSerializedSize);
    }
    for (int i = 0; i < commentTypeTagsList_.size(); i++) {
      output.writeEnumNoTag(commentTypeTagsList_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (showHead_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, showHead_);
    }
    if (showNickname_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, showNickname_);
    }
    if (showFontColor_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, showFontColor_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < colorValueList_.size(); i++) {
        dataSize += computeStringSizeNoTag(colorValueList_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getColorValueListList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < commentTypeTagsList_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeEnumSizeNoTag(commentTypeTagsList_.get(i));
      }
      size += dataSize;
      if (!getCommentTypeTagsListList().isEmpty()) {  size += 1;
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32SizeNoTag(dataSize);
      }commentTypeTagsListMemoizedSerializedSize = dataSize;
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.caesar.crawler.live.douyin.codec.protobuf.LandscapeAreaCommon)) {
      return super.equals(obj);
    }
    org.caesar.crawler.live.douyin.codec.protobuf.LandscapeAreaCommon other = (org.caesar.crawler.live.douyin.codec.protobuf.LandscapeAreaCommon) obj;

    if (getShowHead()
        != other.getShowHead()) return false;
    if (getShowNickname()
        != other.getShowNickname()) return false;
    if (getShowFontColor()
        != other.getShowFontColor()) return false;
    if (!getColorValueListList()
        .equals(other.getColorValueListList())) return false;
    if (!commentTypeTagsList_.equals(other.commentTypeTagsList_)) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SHOWHEAD_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getShowHead());
    hash = (37 * hash) + SHOWNICKNAME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getShowNickname());
    hash = (37 * hash) + SHOWFONTCOLOR_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getShowFontColor());
    if (getColorValueListCount() > 0) {
      hash = (37 * hash) + COLORVALUELIST_FIELD_NUMBER;
      hash = (53 * hash) + getColorValueListList().hashCode();
    }
    if (getCommentTypeTagsListCount() > 0) {
      hash = (37 * hash) + COMMENTTYPETAGSLIST_FIELD_NUMBER;
      hash = (53 * hash) + commentTypeTagsList_.hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.caesar.crawler.live.douyin.codec.protobuf.LandscapeAreaCommon parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.caesar.crawler.live.douyin.codec.protobuf.LandscapeAreaCommon parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.caesar.crawler.live.douyin.codec.protobuf.LandscapeAreaCommon parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.caesar.crawler.live.douyin.codec.protobuf.LandscapeAreaCommon parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.caesar.crawler.live.douyin.codec.protobuf.LandscapeAreaCommon parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.caesar.crawler.live.douyin.codec.protobuf.LandscapeAreaCommon parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.caesar.crawler.live.douyin.codec.protobuf.LandscapeAreaCommon parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.caesar.crawler.live.douyin.codec.protobuf.LandscapeAreaCommon parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.caesar.crawler.live.douyin.codec.protobuf.LandscapeAreaCommon parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.caesar.crawler.live.douyin.codec.protobuf.LandscapeAreaCommon parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.caesar.crawler.live.douyin.codec.protobuf.LandscapeAreaCommon parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.caesar.crawler.live.douyin.codec.protobuf.LandscapeAreaCommon parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.caesar.crawler.live.douyin.codec.protobuf.LandscapeAreaCommon prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code LandscapeAreaCommon}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:LandscapeAreaCommon)
      org.caesar.crawler.live.douyin.codec.protobuf.LandscapeAreaCommonOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.caesar.crawler.live.douyin.codec.protobuf.Douyin.internal_static_LandscapeAreaCommon_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.caesar.crawler.live.douyin.codec.protobuf.Douyin.internal_static_LandscapeAreaCommon_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.caesar.crawler.live.douyin.codec.protobuf.LandscapeAreaCommon.class, org.caesar.crawler.live.douyin.codec.protobuf.LandscapeAreaCommon.Builder.class);
    }

    // Construct using org.caesar.crawler.live.douyin.codec.protobuf.LandscapeAreaCommon.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      showHead_ = false;
      showNickname_ = false;
      showFontColor_ = false;
      colorValueList_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      commentTypeTagsList_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.caesar.crawler.live.douyin.codec.protobuf.Douyin.internal_static_LandscapeAreaCommon_descriptor;
    }

    @Override
    public org.caesar.crawler.live.douyin.codec.protobuf.LandscapeAreaCommon getDefaultInstanceForType() {
      return org.caesar.crawler.live.douyin.codec.protobuf.LandscapeAreaCommon.getDefaultInstance();
    }

    @Override
    public org.caesar.crawler.live.douyin.codec.protobuf.LandscapeAreaCommon build() {
      org.caesar.crawler.live.douyin.codec.protobuf.LandscapeAreaCommon result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public org.caesar.crawler.live.douyin.codec.protobuf.LandscapeAreaCommon buildPartial() {
      org.caesar.crawler.live.douyin.codec.protobuf.LandscapeAreaCommon result = new org.caesar.crawler.live.douyin.codec.protobuf.LandscapeAreaCommon(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.caesar.crawler.live.douyin.codec.protobuf.LandscapeAreaCommon result) {
      if (((bitField0_ & 0x00000010) != 0)) {
        commentTypeTagsList_ = java.util.Collections.unmodifiableList(commentTypeTagsList_);
        bitField0_ = (bitField0_ & ~0x00000010);
      }
      result.commentTypeTagsList_ = commentTypeTagsList_;
    }

    private void buildPartial0(org.caesar.crawler.live.douyin.codec.protobuf.LandscapeAreaCommon result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.showHead_ = showHead_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.showNickname_ = showNickname_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.showFontColor_ = showFontColor_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        colorValueList_.makeImmutable();
        result.colorValueList_ = colorValueList_;
      }
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.caesar.crawler.live.douyin.codec.protobuf.LandscapeAreaCommon) {
        return mergeFrom((org.caesar.crawler.live.douyin.codec.protobuf.LandscapeAreaCommon)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.caesar.crawler.live.douyin.codec.protobuf.LandscapeAreaCommon other) {
      if (other == org.caesar.crawler.live.douyin.codec.protobuf.LandscapeAreaCommon.getDefaultInstance()) return this;
      if (other.getShowHead() != false) {
        setShowHead(other.getShowHead());
      }
      if (other.getShowNickname() != false) {
        setShowNickname(other.getShowNickname());
      }
      if (other.getShowFontColor() != false) {
        setShowFontColor(other.getShowFontColor());
      }
      if (!other.colorValueList_.isEmpty()) {
        if (colorValueList_.isEmpty()) {
          colorValueList_ = other.colorValueList_;
          bitField0_ |= 0x00000008;
        } else {
          ensureColorValueListIsMutable();
          colorValueList_.addAll(other.colorValueList_);
        }
        onChanged();
      }
      if (!other.commentTypeTagsList_.isEmpty()) {
        if (commentTypeTagsList_.isEmpty()) {
          commentTypeTagsList_ = other.commentTypeTagsList_;
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          ensureCommentTypeTagsListIsMutable();
          commentTypeTagsList_.addAll(other.commentTypeTagsList_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              showHead_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              showNickname_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              showFontColor_ = input.readBool();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              String s = input.readStringRequireUtf8();
              ensureColorValueListIsMutable();
              colorValueList_.add(s);
              break;
            } // case 34
            case 40: {
              int tmpRaw = input.readEnum();
              ensureCommentTypeTagsListIsMutable();
              commentTypeTagsList_.add(tmpRaw);
              break;
            } // case 40
            case 42: {
              int length = input.readRawVarint32();
              int oldLimit = input.pushLimit(length);
              while(input.getBytesUntilLimit() > 0) {
                int tmpRaw = input.readEnum();
                ensureCommentTypeTagsListIsMutable();
                commentTypeTagsList_.add(tmpRaw);
              }
              input.popLimit(oldLimit);
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean showHead_ ;
    /**
     * <code>bool showHead = 1;</code>
     * @return The showHead.
     */
    @Override
    public boolean getShowHead() {
      return showHead_;
    }
    /**
     * <code>bool showHead = 1;</code>
     * @param value The showHead to set.
     * @return This builder for chaining.
     */
    public Builder setShowHead(boolean value) {

      showHead_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bool showHead = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearShowHead() {
      bitField0_ = (bitField0_ & ~0x00000001);
      showHead_ = false;
      onChanged();
      return this;
    }

    private boolean showNickname_ ;
    /**
     * <code>bool showNickname = 2;</code>
     * @return The showNickname.
     */
    @Override
    public boolean getShowNickname() {
      return showNickname_;
    }
    /**
     * <code>bool showNickname = 2;</code>
     * @param value The showNickname to set.
     * @return This builder for chaining.
     */
    public Builder setShowNickname(boolean value) {

      showNickname_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bool showNickname = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearShowNickname() {
      bitField0_ = (bitField0_ & ~0x00000002);
      showNickname_ = false;
      onChanged();
      return this;
    }

    private boolean showFontColor_ ;
    /**
     * <code>bool showFontColor = 3;</code>
     * @return The showFontColor.
     */
    @Override
    public boolean getShowFontColor() {
      return showFontColor_;
    }
    /**
     * <code>bool showFontColor = 3;</code>
     * @param value The showFontColor to set.
     * @return This builder for chaining.
     */
    public Builder setShowFontColor(boolean value) {

      showFontColor_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>bool showFontColor = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearShowFontColor() {
      bitField0_ = (bitField0_ & ~0x00000004);
      showFontColor_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList colorValueList_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureColorValueListIsMutable() {
      if (!colorValueList_.isModifiable()) {
        colorValueList_ = new com.google.protobuf.LazyStringArrayList(colorValueList_);
      }
      bitField0_ |= 0x00000008;
    }
    /**
     * <code>repeated string colorValueList = 4;</code>
     * @return A list containing the colorValueList.
     */
    public com.google.protobuf.ProtocolStringList
        getColorValueListList() {
      colorValueList_.makeImmutable();
      return colorValueList_;
    }
    /**
     * <code>repeated string colorValueList = 4;</code>
     * @return The count of colorValueList.
     */
    public int getColorValueListCount() {
      return colorValueList_.size();
    }
    /**
     * <code>repeated string colorValueList = 4;</code>
     * @param index The index of the element to return.
     * @return The colorValueList at the given index.
     */
    public String getColorValueList(int index) {
      return colorValueList_.get(index);
    }
    /**
     * <code>repeated string colorValueList = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the colorValueList at the given index.
     */
    public com.google.protobuf.ByteString
        getColorValueListBytes(int index) {
      return colorValueList_.getByteString(index);
    }
    /**
     * <code>repeated string colorValueList = 4;</code>
     * @param index The index to set the value at.
     * @param value The colorValueList to set.
     * @return This builder for chaining.
     */
    public Builder setColorValueList(
        int index, String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureColorValueListIsMutable();
      colorValueList_.set(index, value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string colorValueList = 4;</code>
     * @param value The colorValueList to add.
     * @return This builder for chaining.
     */
    public Builder addColorValueList(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureColorValueListIsMutable();
      colorValueList_.add(value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string colorValueList = 4;</code>
     * @param values The colorValueList to add.
     * @return This builder for chaining.
     */
    public Builder addAllColorValueList(
        Iterable<String> values) {
      ensureColorValueListIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, colorValueList_);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string colorValueList = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearColorValueList() {
      colorValueList_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000008);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string colorValueList = 4;</code>
     * @param value The bytes of the colorValueList to add.
     * @return This builder for chaining.
     */
    public Builder addColorValueListBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureColorValueListIsMutable();
      colorValueList_.add(value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.util.List<Integer> commentTypeTagsList_ =
      java.util.Collections.emptyList();
    private void ensureCommentTypeTagsListIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        commentTypeTagsList_ = new java.util.ArrayList<Integer>(commentTypeTagsList_);
        bitField0_ |= 0x00000010;
      }
    }
    /**
     * <code>repeated .CommentTypeTag commentTypeTagsList = 5;</code>
     * @return A list containing the commentTypeTagsList.
     */
    public java.util.List<org.caesar.crawler.live.douyin.codec.protobuf.CommentTypeTag> getCommentTypeTagsListList() {
      return new com.google.protobuf.Internal.ListAdapter<
          Integer, org.caesar.crawler.live.douyin.codec.protobuf.CommentTypeTag>(commentTypeTagsList_, commentTypeTagsList_converter_);
    }
    /**
     * <code>repeated .CommentTypeTag commentTypeTagsList = 5;</code>
     * @return The count of commentTypeTagsList.
     */
    public int getCommentTypeTagsListCount() {
      return commentTypeTagsList_.size();
    }
    /**
     * <code>repeated .CommentTypeTag commentTypeTagsList = 5;</code>
     * @param index The index of the element to return.
     * @return The commentTypeTagsList at the given index.
     */
    public org.caesar.crawler.live.douyin.codec.protobuf.CommentTypeTag getCommentTypeTagsList(int index) {
      return commentTypeTagsList_converter_.convert(commentTypeTagsList_.get(index));
    }
    /**
     * <code>repeated .CommentTypeTag commentTypeTagsList = 5;</code>
     * @param index The index to set the value at.
     * @param value The commentTypeTagsList to set.
     * @return This builder for chaining.
     */
    public Builder setCommentTypeTagsList(
        int index, org.caesar.crawler.live.douyin.codec.protobuf.CommentTypeTag value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureCommentTypeTagsListIsMutable();
      commentTypeTagsList_.set(index, value.getNumber());
      onChanged();
      return this;
    }
    /**
     * <code>repeated .CommentTypeTag commentTypeTagsList = 5;</code>
     * @param value The commentTypeTagsList to add.
     * @return This builder for chaining.
     */
    public Builder addCommentTypeTagsList(org.caesar.crawler.live.douyin.codec.protobuf.CommentTypeTag value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureCommentTypeTagsListIsMutable();
      commentTypeTagsList_.add(value.getNumber());
      onChanged();
      return this;
    }
    /**
     * <code>repeated .CommentTypeTag commentTypeTagsList = 5;</code>
     * @param values The commentTypeTagsList to add.
     * @return This builder for chaining.
     */
    public Builder addAllCommentTypeTagsList(
        Iterable<? extends org.caesar.crawler.live.douyin.codec.protobuf.CommentTypeTag> values) {
      ensureCommentTypeTagsListIsMutable();
      for (org.caesar.crawler.live.douyin.codec.protobuf.CommentTypeTag value : values) {
        commentTypeTagsList_.add(value.getNumber());
      }
      onChanged();
      return this;
    }
    /**
     * <code>repeated .CommentTypeTag commentTypeTagsList = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCommentTypeTagsList() {
      commentTypeTagsList_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>repeated .CommentTypeTag commentTypeTagsList = 5;</code>
     * @return A list containing the enum numeric values on the wire for commentTypeTagsList.
     */
    public java.util.List<Integer>
    getCommentTypeTagsListValueList() {
      return java.util.Collections.unmodifiableList(commentTypeTagsList_);
    }
    /**
     * <code>repeated .CommentTypeTag commentTypeTagsList = 5;</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of commentTypeTagsList at the given index.
     */
    public int getCommentTypeTagsListValue(int index) {
      return commentTypeTagsList_.get(index);
    }
    /**
     * <code>repeated .CommentTypeTag commentTypeTagsList = 5;</code>
     * @param index The index to set the value at.
     * @param value The enum numeric value on the wire for commentTypeTagsList to set.
     * @return This builder for chaining.
     */
    public Builder setCommentTypeTagsListValue(
        int index, int value) {
      ensureCommentTypeTagsListIsMutable();
      commentTypeTagsList_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated .CommentTypeTag commentTypeTagsList = 5;</code>
     * @param value The enum numeric value on the wire for commentTypeTagsList to add.
     * @return This builder for chaining.
     */
    public Builder addCommentTypeTagsListValue(int value) {
      ensureCommentTypeTagsListIsMutable();
      commentTypeTagsList_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated .CommentTypeTag commentTypeTagsList = 5;</code>
     * @param values The enum numeric values on the wire for commentTypeTagsList to add.
     * @return This builder for chaining.
     */
    public Builder addAllCommentTypeTagsListValue(
        Iterable<Integer> values) {
      ensureCommentTypeTagsListIsMutable();
      for (int value : values) {
        commentTypeTagsList_.add(value);
      }
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:LandscapeAreaCommon)
  }

  // @@protoc_insertion_point(class_scope:LandscapeAreaCommon)
  private static final org.caesar.crawler.live.douyin.codec.protobuf.LandscapeAreaCommon DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.caesar.crawler.live.douyin.codec.protobuf.LandscapeAreaCommon();
  }

  public static org.caesar.crawler.live.douyin.codec.protobuf.LandscapeAreaCommon getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LandscapeAreaCommon>
      PARSER = new com.google.protobuf.AbstractParser<LandscapeAreaCommon>() {
    @Override
    public LandscapeAreaCommon parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<LandscapeAreaCommon> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<LandscapeAreaCommon> getParserForType() {
    return PARSER;
  }

  @Override
  public org.caesar.crawler.live.douyin.codec.protobuf.LandscapeAreaCommon getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

