// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

// Protobuf Java Version: 3.25.5
package org.caesar.crawler.live.douyin.codec.protobuf;

public interface LikeMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LikeMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Common common = 1;</code>
   * @return Whether the common field is set.
   */
  boolean hasCommon();
  /**
   * <code>.Common common = 1;</code>
   * @return The common.
   */
  org.caesar.crawler.live.douyin.codec.protobuf.Common getCommon();
  /**
   * <code>.Common common = 1;</code>
   */
  org.caesar.crawler.live.douyin.codec.protobuf.CommonOrBuilder getCommonOrBuilder();

  /**
   * <code>uint64 count = 2;</code>
   * @return The count.
   */
  long getCount();

  /**
   * <code>uint64 total = 3;</code>
   * @return The total.
   */
  long getTotal();

  /**
   * <code>uint64 color = 4;</code>
   * @return The color.
   */
  long getColor();

  /**
   * <code>.User user = 5;</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <code>.User user = 5;</code>
   * @return The user.
   */
  org.caesar.crawler.live.douyin.codec.protobuf.User getUser();
  /**
   * <code>.User user = 5;</code>
   */
  org.caesar.crawler.live.douyin.codec.protobuf.UserOrBuilder getUserOrBuilder();

  /**
   * <code>string icon = 6;</code>
   * @return The icon.
   */
  String getIcon();
  /**
   * <code>string icon = 6;</code>
   * @return The bytes for icon.
   */
  com.google.protobuf.ByteString
      getIconBytes();

  /**
   * <code>.DoubleLikeDetail doubleLikeDetail = 7;</code>
   * @return Whether the doubleLikeDetail field is set.
   */
  boolean hasDoubleLikeDetail();
  /**
   * <code>.DoubleLikeDetail doubleLikeDetail = 7;</code>
   * @return The doubleLikeDetail.
   */
  org.caesar.crawler.live.douyin.codec.protobuf.DoubleLikeDetail getDoubleLikeDetail();
  /**
   * <code>.DoubleLikeDetail doubleLikeDetail = 7;</code>
   */
  org.caesar.crawler.live.douyin.codec.protobuf.DoubleLikeDetailOrBuilder getDoubleLikeDetailOrBuilder();

  /**
   * <code>.DisplayControlInfo displayControlInfo = 8;</code>
   * @return Whether the displayControlInfo field is set.
   */
  boolean hasDisplayControlInfo();
  /**
   * <code>.DisplayControlInfo displayControlInfo = 8;</code>
   * @return The displayControlInfo.
   */
  org.caesar.crawler.live.douyin.codec.protobuf.DisplayControlInfo getDisplayControlInfo();
  /**
   * <code>.DisplayControlInfo displayControlInfo = 8;</code>
   */
  org.caesar.crawler.live.douyin.codec.protobuf.DisplayControlInfoOrBuilder getDisplayControlInfoOrBuilder();

  /**
   * <code>uint64 linkmicGuestUid = 9;</code>
   * @return The linkmicGuestUid.
   */
  long getLinkmicGuestUid();

  /**
   * <code>string scene = 10;</code>
   * @return The scene.
   */
  String getScene();
  /**
   * <code>string scene = 10;</code>
   * @return The bytes for scene.
   */
  com.google.protobuf.ByteString
      getSceneBytes();

  /**
   * <code>.PicoDisplayInfo picoDisplayInfo = 11;</code>
   * @return Whether the picoDisplayInfo field is set.
   */
  boolean hasPicoDisplayInfo();
  /**
   * <code>.PicoDisplayInfo picoDisplayInfo = 11;</code>
   * @return The picoDisplayInfo.
   */
  org.caesar.crawler.live.douyin.codec.protobuf.PicoDisplayInfo getPicoDisplayInfo();
  /**
   * <code>.PicoDisplayInfo picoDisplayInfo = 11;</code>
   */
  org.caesar.crawler.live.douyin.codec.protobuf.PicoDisplayInfoOrBuilder getPicoDisplayInfoOrBuilder();
}
