// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

// Protobuf Java Version: 3.25.5
package org.caesar.crawler.live.douyin.codec.protobuf;

public interface PayGradeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PayGrade)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 totalDiamondCount = 1;</code>
   * @return The totalDiamondCount.
   */
  long getTotalDiamondCount();

  /**
   * <code>.Image diamondIcon = 2;</code>
   * @return Whether the diamondIcon field is set.
   */
  boolean hasDiamondIcon();
  /**
   * <code>.Image diamondIcon = 2;</code>
   * @return The diamondIcon.
   */
  org.caesar.crawler.live.douyin.codec.protobuf.Image getDiamondIcon();
  /**
   * <code>.Image diamondIcon = 2;</code>
   */
  org.caesar.crawler.live.douyin.codec.protobuf.ImageOrBuilder getDiamondIconOrBuilder();

  /**
   * <code>string name = 3;</code>
   * @return The name.
   */
  String getName();
  /**
   * <code>string name = 3;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.Image icon = 4;</code>
   * @return Whether the icon field is set.
   */
  boolean hasIcon();
  /**
   * <code>.Image icon = 4;</code>
   * @return The icon.
   */
  org.caesar.crawler.live.douyin.codec.protobuf.Image getIcon();
  /**
   * <code>.Image icon = 4;</code>
   */
  org.caesar.crawler.live.douyin.codec.protobuf.ImageOrBuilder getIconOrBuilder();

  /**
   * <code>string nextName = 5;</code>
   * @return The nextName.
   */
  String getNextName();
  /**
   * <code>string nextName = 5;</code>
   * @return The bytes for nextName.
   */
  com.google.protobuf.ByteString
      getNextNameBytes();

  /**
   * <code>int64 level = 6;</code>
   * @return The level.
   */
  long getLevel();

  /**
   * <code>.Image nextIcon = 7;</code>
   * @return Whether the nextIcon field is set.
   */
  boolean hasNextIcon();
  /**
   * <code>.Image nextIcon = 7;</code>
   * @return The nextIcon.
   */
  org.caesar.crawler.live.douyin.codec.protobuf.Image getNextIcon();
  /**
   * <code>.Image nextIcon = 7;</code>
   */
  org.caesar.crawler.live.douyin.codec.protobuf.ImageOrBuilder getNextIconOrBuilder();

  /**
   * <code>int64 nextDiamond = 8;</code>
   * @return The nextDiamond.
   */
  long getNextDiamond();

  /**
   * <code>int64 nowDiamond = 9;</code>
   * @return The nowDiamond.
   */
  long getNowDiamond();

  /**
   * <code>int64 thisGradeMinDiamond = 10;</code>
   * @return The thisGradeMinDiamond.
   */
  long getThisGradeMinDiamond();

  /**
   * <code>int64 thisGradeMaxDiamond = 11;</code>
   * @return The thisGradeMaxDiamond.
   */
  long getThisGradeMaxDiamond();

  /**
   * <code>int64 payDiamondBak = 12;</code>
   * @return The payDiamondBak.
   */
  long getPayDiamondBak();

  /**
   * <code>string gradeDescribe = 13;</code>
   * @return The gradeDescribe.
   */
  String getGradeDescribe();
  /**
   * <code>string gradeDescribe = 13;</code>
   * @return The bytes for gradeDescribe.
   */
  com.google.protobuf.ByteString
      getGradeDescribeBytes();

  /**
   * <code>repeated .GradeIcon gradeIconList = 14;</code>
   */
  java.util.List<org.caesar.crawler.live.douyin.codec.protobuf.GradeIcon>
      getGradeIconListList();
  /**
   * <code>repeated .GradeIcon gradeIconList = 14;</code>
   */
  org.caesar.crawler.live.douyin.codec.protobuf.GradeIcon getGradeIconList(int index);
  /**
   * <code>repeated .GradeIcon gradeIconList = 14;</code>
   */
  int getGradeIconListCount();
  /**
   * <code>repeated .GradeIcon gradeIconList = 14;</code>
   */
  java.util.List<? extends org.caesar.crawler.live.douyin.codec.protobuf.GradeIconOrBuilder>
      getGradeIconListOrBuilderList();
  /**
   * <code>repeated .GradeIcon gradeIconList = 14;</code>
   */
  org.caesar.crawler.live.douyin.codec.protobuf.GradeIconOrBuilder getGradeIconListOrBuilder(
      int index);

  /**
   * <code>int64 screenChatType = 15;</code>
   * @return The screenChatType.
   */
  long getScreenChatType();

  /**
   * <code>.Image imIcon = 16;</code>
   * @return Whether the imIcon field is set.
   */
  boolean hasImIcon();
  /**
   * <code>.Image imIcon = 16;</code>
   * @return The imIcon.
   */
  org.caesar.crawler.live.douyin.codec.protobuf.Image getImIcon();
  /**
   * <code>.Image imIcon = 16;</code>
   */
  org.caesar.crawler.live.douyin.codec.protobuf.ImageOrBuilder getImIconOrBuilder();

  /**
   * <code>.Image imIconWithLevel = 17;</code>
   * @return Whether the imIconWithLevel field is set.
   */
  boolean hasImIconWithLevel();
  /**
   * <code>.Image imIconWithLevel = 17;</code>
   * @return The imIconWithLevel.
   */
  org.caesar.crawler.live.douyin.codec.protobuf.Image getImIconWithLevel();
  /**
   * <code>.Image imIconWithLevel = 17;</code>
   */
  org.caesar.crawler.live.douyin.codec.protobuf.ImageOrBuilder getImIconWithLevelOrBuilder();

  /**
   * <code>.Image liveIcon = 18;</code>
   * @return Whether the liveIcon field is set.
   */
  boolean hasLiveIcon();
  /**
   * <code>.Image liveIcon = 18;</code>
   * @return The liveIcon.
   */
  org.caesar.crawler.live.douyin.codec.protobuf.Image getLiveIcon();
  /**
   * <code>.Image liveIcon = 18;</code>
   */
  org.caesar.crawler.live.douyin.codec.protobuf.ImageOrBuilder getLiveIconOrBuilder();

  /**
   * <code>.Image newImIconWithLevel = 19;</code>
   * @return Whether the newImIconWithLevel field is set.
   */
  boolean hasNewImIconWithLevel();
  /**
   * <code>.Image newImIconWithLevel = 19;</code>
   * @return The newImIconWithLevel.
   */
  org.caesar.crawler.live.douyin.codec.protobuf.Image getNewImIconWithLevel();
  /**
   * <code>.Image newImIconWithLevel = 19;</code>
   */
  org.caesar.crawler.live.douyin.codec.protobuf.ImageOrBuilder getNewImIconWithLevelOrBuilder();

  /**
   * <code>.Image newLiveIcon = 20;</code>
   * @return Whether the newLiveIcon field is set.
   */
  boolean hasNewLiveIcon();
  /**
   * <code>.Image newLiveIcon = 20;</code>
   * @return The newLiveIcon.
   */
  org.caesar.crawler.live.douyin.codec.protobuf.Image getNewLiveIcon();
  /**
   * <code>.Image newLiveIcon = 20;</code>
   */
  org.caesar.crawler.live.douyin.codec.protobuf.ImageOrBuilder getNewLiveIconOrBuilder();

  /**
   * <code>int64 upgradeNeedConsume = 21;</code>
   * @return The upgradeNeedConsume.
   */
  long getUpgradeNeedConsume();

  /**
   * <code>string nextPrivileges = 22;</code>
   * @return The nextPrivileges.
   */
  String getNextPrivileges();
  /**
   * <code>string nextPrivileges = 22;</code>
   * @return The bytes for nextPrivileges.
   */
  com.google.protobuf.ByteString
      getNextPrivilegesBytes();

  /**
   * <code>.Image background = 23;</code>
   * @return Whether the background field is set.
   */
  boolean hasBackground();
  /**
   * <code>.Image background = 23;</code>
   * @return The background.
   */
  org.caesar.crawler.live.douyin.codec.protobuf.Image getBackground();
  /**
   * <code>.Image background = 23;</code>
   */
  org.caesar.crawler.live.douyin.codec.protobuf.ImageOrBuilder getBackgroundOrBuilder();

  /**
   * <code>.Image backgroundBack = 24;</code>
   * @return Whether the backgroundBack field is set.
   */
  boolean hasBackgroundBack();
  /**
   * <code>.Image backgroundBack = 24;</code>
   * @return The backgroundBack.
   */
  org.caesar.crawler.live.douyin.codec.protobuf.Image getBackgroundBack();
  /**
   * <code>.Image backgroundBack = 24;</code>
   */
  org.caesar.crawler.live.douyin.codec.protobuf.ImageOrBuilder getBackgroundBackOrBuilder();

  /**
   * <code>int64 score = 25;</code>
   * @return The score.
   */
  long getScore();

  /**
   * <code>.GradeBuffInfo buffInfo = 26;</code>
   * @return Whether the buffInfo field is set.
   */
  boolean hasBuffInfo();
  /**
   * <code>.GradeBuffInfo buffInfo = 26;</code>
   * @return The buffInfo.
   */
  org.caesar.crawler.live.douyin.codec.protobuf.GradeBuffInfo getBuffInfo();
  /**
   * <code>.GradeBuffInfo buffInfo = 26;</code>
   */
  org.caesar.crawler.live.douyin.codec.protobuf.GradeBuffInfoOrBuilder getBuffInfoOrBuilder();

  /**
   * <code>string gradeBanner = 1001;</code>
   * @return The gradeBanner.
   */
  String getGradeBanner();
  /**
   * <code>string gradeBanner = 1001;</code>
   * @return The bytes for gradeBanner.
   */
  com.google.protobuf.ByteString
      getGradeBannerBytes();

  /**
   * <code>.Image profileDialogBg = 1002;</code>
   * @return Whether the profileDialogBg field is set.
   */
  boolean hasProfileDialogBg();
  /**
   * <code>.Image profileDialogBg = 1002;</code>
   * @return The profileDialogBg.
   */
  org.caesar.crawler.live.douyin.codec.protobuf.Image getProfileDialogBg();
  /**
   * <code>.Image profileDialogBg = 1002;</code>
   */
  org.caesar.crawler.live.douyin.codec.protobuf.ImageOrBuilder getProfileDialogBgOrBuilder();

  /**
   * <code>.Image profileDialogBgBack = 1003;</code>
   * @return Whether the profileDialogBgBack field is set.
   */
  boolean hasProfileDialogBgBack();
  /**
   * <code>.Image profileDialogBgBack = 1003;</code>
   * @return The profileDialogBgBack.
   */
  org.caesar.crawler.live.douyin.codec.protobuf.Image getProfileDialogBgBack();
  /**
   * <code>.Image profileDialogBgBack = 1003;</code>
   */
  org.caesar.crawler.live.douyin.codec.protobuf.ImageOrBuilder getProfileDialogBgBackOrBuilder();
}
