// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

// Protobuf Java Version: 3.25.5
package org.caesar.crawler.live.douyin.codec.protobuf;

public interface PicoDisplayInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PicoDisplayInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 comboSumCount = 1;</code>
   * @return The comboSumCount.
   */
  long getComboSumCount();

  /**
   * <code>string emoji = 2;</code>
   * @return The emoji.
   */
  String getEmoji();
  /**
   * <code>string emoji = 2;</code>
   * @return The bytes for emoji.
   */
  com.google.protobuf.ByteString
      getEmojiBytes();

  /**
   * <code>.Image emojiIcon = 3;</code>
   * @return Whether the emojiIcon field is set.
   */
  boolean hasEmojiIcon();
  /**
   * <code>.Image emojiIcon = 3;</code>
   * @return The emojiIcon.
   */
  org.caesar.crawler.live.douyin.codec.protobuf.Image getEmojiIcon();
  /**
   * <code>.Image emojiIcon = 3;</code>
   */
  org.caesar.crawler.live.douyin.codec.protobuf.ImageOrBuilder getEmojiIconOrBuilder();

  /**
   * <code>string emojiText = 4;</code>
   * @return The emojiText.
   */
  String getEmojiText();
  /**
   * <code>string emojiText = 4;</code>
   * @return The bytes for emojiText.
   */
  com.google.protobuf.ByteString
      getEmojiTextBytes();
}
