// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

// Protobuf Java Version: 3.25.5
package org.caesar.crawler.live.douyin.codec.protobuf;

public interface PreMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PreMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 cmd = 1;</code>
   * @return The cmd.
   */
  int getCmd();

  /**
   * <code>uint32 sequenceId = 2;</code>
   * @return The sequenceId.
   */
  int getSequenceId();

  /**
   * <code>string sdkVersion = 3;</code>
   * @return The sdkVersion.
   */
  String getSdkVersion();
  /**
   * <code>string sdkVersion = 3;</code>
   * @return The bytes for sdkVersion.
   */
  com.google.protobuf.ByteString
      getSdkVersionBytes();

  /**
   * <code>string token = 4;</code>
   * @return The token.
   */
  String getToken();
  /**
   * <code>string token = 4;</code>
   * @return The bytes for token.
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <code>uint32 refer = 5;</code>
   * @return The refer.
   */
  int getRefer();

  /**
   * <code>uint32 inboxType = 6;</code>
   * @return The inboxType.
   */
  int getInboxType();

  /**
   * <code>string buildNumber = 7;</code>
   * @return The buildNumber.
   */
  String getBuildNumber();
  /**
   * <code>string buildNumber = 7;</code>
   * @return The bytes for buildNumber.
   */
  com.google.protobuf.ByteString
      getBuildNumberBytes();

  /**
   * <code>.SendMessageBody sendMessageBody = 8;</code>
   * @return Whether the sendMessageBody field is set.
   */
  boolean hasSendMessageBody();
  /**
   * <code>.SendMessageBody sendMessageBody = 8;</code>
   * @return The sendMessageBody.
   */
  org.caesar.crawler.live.douyin.codec.protobuf.SendMessageBody getSendMessageBody();
  /**
   * <code>.SendMessageBody sendMessageBody = 8;</code>
   */
  org.caesar.crawler.live.douyin.codec.protobuf.SendMessageBodyOrBuilder getSendMessageBodyOrBuilder();

  /**
   * <pre>
   * 字段名待定
   * </pre>
   *
   * <code>string aa = 9;</code>
   * @return The aa.
   */
  String getAa();
  /**
   * <pre>
   * 字段名待定
   * </pre>
   *
   * <code>string aa = 9;</code>
   * @return The bytes for aa.
   */
  com.google.protobuf.ByteString
      getAaBytes();

  /**
   * <code>string devicePlatform = 11;</code>
   * @return The devicePlatform.
   */
  String getDevicePlatform();
  /**
   * <code>string devicePlatform = 11;</code>
   * @return The bytes for devicePlatform.
   */
  com.google.protobuf.ByteString
      getDevicePlatformBytes();

  /**
   * <code>repeated .HeadersList headers = 15;</code>
   */
  java.util.List<org.caesar.crawler.live.douyin.codec.protobuf.HeadersList>
      getHeadersList();
  /**
   * <code>repeated .HeadersList headers = 15;</code>
   */
  org.caesar.crawler.live.douyin.codec.protobuf.HeadersList getHeaders(int index);
  /**
   * <code>repeated .HeadersList headers = 15;</code>
   */
  int getHeadersCount();
  /**
   * <code>repeated .HeadersList headers = 15;</code>
   */
  java.util.List<? extends org.caesar.crawler.live.douyin.codec.protobuf.HeadersListOrBuilder>
      getHeadersOrBuilderList();
  /**
   * <code>repeated .HeadersList headers = 15;</code>
   */
  org.caesar.crawler.live.douyin.codec.protobuf.HeadersListOrBuilder getHeadersOrBuilder(
      int index);

  /**
   * <code>uint32 authType = 18;</code>
   * @return The authType.
   */
  int getAuthType();

  /**
   * <code>string biz = 21;</code>
   * @return The biz.
   */
  String getBiz();
  /**
   * <code>string biz = 21;</code>
   * @return The bytes for biz.
   */
  com.google.protobuf.ByteString
      getBizBytes();

  /**
   * <code>string access = 22;</code>
   * @return The access.
   */
  String getAccess();
  /**
   * <code>string access = 22;</code>
   * @return The bytes for access.
   */
  com.google.protobuf.ByteString
      getAccessBytes();
}
