// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

// Protobuf Java Version: 3.25.5
package org.caesar.crawler.live.douyin.codec.protobuf;

public interface RanklistHourEntrance_DetailOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RanklistHourEntrance_Detail)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 假设 pages 是 RanklistHourEntrance_Page 类型
   * </pre>
   *
   * <code>repeated .RanklistHourEntrance_Page pages = 1;</code>
   */
  java.util.List<org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page>
      getPagesList();
  /**
   * <pre>
   * 假设 pages 是 RanklistHourEntrance_Page 类型
   * </pre>
   *
   * <code>repeated .RanklistHourEntrance_Page pages = 1;</code>
   */
  org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page getPages(int index);
  /**
   * <pre>
   * 假设 pages 是 RanklistHourEntrance_Page 类型
   * </pre>
   *
   * <code>repeated .RanklistHourEntrance_Page pages = 1;</code>
   */
  int getPagesCount();
  /**
   * <pre>
   * 假设 pages 是 RanklistHourEntrance_Page 类型
   * </pre>
   *
   * <code>repeated .RanklistHourEntrance_Page pages = 1;</code>
   */
  java.util.List<? extends org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_PageOrBuilder>
      getPagesOrBuilderList();
  /**
   * <pre>
   * 假设 pages 是 RanklistHourEntrance_Page 类型
   * </pre>
   *
   * <code>repeated .RanklistHourEntrance_Page pages = 1;</code>
   */
  org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_PageOrBuilder getPagesOrBuilder(
      int index);

  /**
   * <pre>
   * 排名列表类型
   * </pre>
   *
   * <code>int32 ranklist_type = 2;</code>
   * @return The ranklistType.
   */
  int getRanklistType();

  /**
   * <pre>
   * 标题
   * </pre>
   *
   * <code>string title = 3;</code>
   * @return The title.
   */
  String getTitle();
  /**
   * <pre>
   * 标题
   * </pre>
   *
   * <code>string title = 3;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <pre>
   * 排名列表额外信息
   * </pre>
   *
   * <code>string ranklist_extra = 4;</code>
   * @return The ranklistExtra.
   */
  String getRanklistExtra();
  /**
   * <pre>
   * 排名列表额外信息
   * </pre>
   *
   * <code>string ranklist_extra = 4;</code>
   * @return The bytes for ranklistExtra.
   */
  com.google.protobuf.ByteString
      getRanklistExtraBytes();

  /**
   * <pre>
   * 入口额外信息
   * </pre>
   *
   * <code>string entrance_extra = 5;</code>
   * @return The entranceExtra.
   */
  String getEntranceExtra();
  /**
   * <pre>
   * 入口额外信息
   * </pre>
   *
   * <code>string entrance_extra = 5;</code>
   * @return The bytes for entranceExtra.
   */
  com.google.protobuf.ByteString
      getEntranceExtraBytes();

  /**
   * <pre>
   * 模式
   * </pre>
   *
   * <code>string schema = 6;</code>
   * @return The schema.
   */
  String getSchema();
  /**
   * <pre>
   * 模式
   * </pre>
   *
   * <code>string schema = 6;</code>
   * @return The bytes for schema.
   */
  com.google.protobuf.ByteString
      getSchemaBytes();
}
