// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

// Protobuf Java Version: 3.25.5
package org.caesar.crawler.live.douyin.codec.protobuf;

/**
 * Protobuf type {@code RanklistHourEntrance_Detail}
 */
public final class RanklistHourEntrance_Detail extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:RanklistHourEntrance_Detail)
    RanklistHourEntrance_DetailOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RanklistHourEntrance_Detail.newBuilder() to construct.
  private RanklistHourEntrance_Detail(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RanklistHourEntrance_Detail() {
    pages_ = java.util.Collections.emptyList();
    title_ = "";
    ranklistExtra_ = "";
    entranceExtra_ = "";
    schema_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new RanklistHourEntrance_Detail();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.caesar.crawler.live.douyin.codec.protobuf.Douyin.internal_static_RanklistHourEntrance_Detail_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.caesar.crawler.live.douyin.codec.protobuf.Douyin.internal_static_RanklistHourEntrance_Detail_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Detail.class, org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Detail.Builder.class);
  }

  public static final int PAGES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page> pages_;
  /**
   * <pre>
   * 假设 pages 是 RanklistHourEntrance_Page 类型
   * </pre>
   *
   * <code>repeated .RanklistHourEntrance_Page pages = 1;</code>
   */
  @Override
  public java.util.List<org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page> getPagesList() {
    return pages_;
  }
  /**
   * <pre>
   * 假设 pages 是 RanklistHourEntrance_Page 类型
   * </pre>
   *
   * <code>repeated .RanklistHourEntrance_Page pages = 1;</code>
   */
  @Override
  public java.util.List<? extends org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_PageOrBuilder>
      getPagesOrBuilderList() {
    return pages_;
  }
  /**
   * <pre>
   * 假设 pages 是 RanklistHourEntrance_Page 类型
   * </pre>
   *
   * <code>repeated .RanklistHourEntrance_Page pages = 1;</code>
   */
  @Override
  public int getPagesCount() {
    return pages_.size();
  }
  /**
   * <pre>
   * 假设 pages 是 RanklistHourEntrance_Page 类型
   * </pre>
   *
   * <code>repeated .RanklistHourEntrance_Page pages = 1;</code>
   */
  @Override
  public org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page getPages(int index) {
    return pages_.get(index);
  }
  /**
   * <pre>
   * 假设 pages 是 RanklistHourEntrance_Page 类型
   * </pre>
   *
   * <code>repeated .RanklistHourEntrance_Page pages = 1;</code>
   */
  @Override
  public org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_PageOrBuilder getPagesOrBuilder(
      int index) {
    return pages_.get(index);
  }

  public static final int RANKLIST_TYPE_FIELD_NUMBER = 2;
  private int ranklistType_ = 0;
  /**
   * <pre>
   * 排名列表类型
   * </pre>
   *
   * <code>int32 ranklist_type = 2;</code>
   * @return The ranklistType.
   */
  @Override
  public int getRanklistType() {
    return ranklistType_;
  }

  public static final int TITLE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile Object title_ = "";
  /**
   * <pre>
   * 标题
   * </pre>
   *
   * <code>string title = 3;</code>
   * @return The title.
   */
  @Override
  public String getTitle() {
    Object ref = title_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      title_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 标题
   * </pre>
   *
   * <code>string title = 3;</code>
   * @return The bytes for title.
   */
  @Override
  public com.google.protobuf.ByteString
      getTitleBytes() {
    Object ref = title_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RANKLIST_EXTRA_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile Object ranklistExtra_ = "";
  /**
   * <pre>
   * 排名列表额外信息
   * </pre>
   *
   * <code>string ranklist_extra = 4;</code>
   * @return The ranklistExtra.
   */
  @Override
  public String getRanklistExtra() {
    Object ref = ranklistExtra_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      ranklistExtra_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 排名列表额外信息
   * </pre>
   *
   * <code>string ranklist_extra = 4;</code>
   * @return The bytes for ranklistExtra.
   */
  @Override
  public com.google.protobuf.ByteString
      getRanklistExtraBytes() {
    Object ref = ranklistExtra_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      ranklistExtra_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENTRANCE_EXTRA_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile Object entranceExtra_ = "";
  /**
   * <pre>
   * 入口额外信息
   * </pre>
   *
   * <code>string entrance_extra = 5;</code>
   * @return The entranceExtra.
   */
  @Override
  public String getEntranceExtra() {
    Object ref = entranceExtra_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      entranceExtra_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 入口额外信息
   * </pre>
   *
   * <code>string entrance_extra = 5;</code>
   * @return The bytes for entranceExtra.
   */
  @Override
  public com.google.protobuf.ByteString
      getEntranceExtraBytes() {
    Object ref = entranceExtra_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      entranceExtra_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SCHEMA_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile Object schema_ = "";
  /**
   * <pre>
   * 模式
   * </pre>
   *
   * <code>string schema = 6;</code>
   * @return The schema.
   */
  @Override
  public String getSchema() {
    Object ref = schema_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      schema_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 模式
   * </pre>
   *
   * <code>string schema = 6;</code>
   * @return The bytes for schema.
   */
  @Override
  public com.google.protobuf.ByteString
      getSchemaBytes() {
    Object ref = schema_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      schema_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < pages_.size(); i++) {
      output.writeMessage(1, pages_.get(i));
    }
    if (ranklistType_ != 0) {
      output.writeInt32(2, ranklistType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, title_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ranklistExtra_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, ranklistExtra_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(entranceExtra_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, entranceExtra_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(schema_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, schema_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < pages_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, pages_.get(i));
    }
    if (ranklistType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, ranklistType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, title_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ranklistExtra_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, ranklistExtra_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(entranceExtra_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, entranceExtra_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(schema_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, schema_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Detail)) {
      return super.equals(obj);
    }
    org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Detail other = (org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Detail) obj;

    if (!getPagesList()
        .equals(other.getPagesList())) return false;
    if (getRanklistType()
        != other.getRanklistType()) return false;
    if (!getTitle()
        .equals(other.getTitle())) return false;
    if (!getRanklistExtra()
        .equals(other.getRanklistExtra())) return false;
    if (!getEntranceExtra()
        .equals(other.getEntranceExtra())) return false;
    if (!getSchema()
        .equals(other.getSchema())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getPagesCount() > 0) {
      hash = (37 * hash) + PAGES_FIELD_NUMBER;
      hash = (53 * hash) + getPagesList().hashCode();
    }
    hash = (37 * hash) + RANKLIST_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getRanklistType();
    hash = (37 * hash) + TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTitle().hashCode();
    hash = (37 * hash) + RANKLIST_EXTRA_FIELD_NUMBER;
    hash = (53 * hash) + getRanklistExtra().hashCode();
    hash = (37 * hash) + ENTRANCE_EXTRA_FIELD_NUMBER;
    hash = (53 * hash) + getEntranceExtra().hashCode();
    hash = (37 * hash) + SCHEMA_FIELD_NUMBER;
    hash = (53 * hash) + getSchema().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Detail parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Detail parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Detail parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Detail parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Detail parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Detail parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Detail parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Detail parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Detail parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Detail parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Detail parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Detail parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Detail prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code RanklistHourEntrance_Detail}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:RanklistHourEntrance_Detail)
      org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_DetailOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.caesar.crawler.live.douyin.codec.protobuf.Douyin.internal_static_RanklistHourEntrance_Detail_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.caesar.crawler.live.douyin.codec.protobuf.Douyin.internal_static_RanklistHourEntrance_Detail_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Detail.class, org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Detail.Builder.class);
    }

    // Construct using org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Detail.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (pagesBuilder_ == null) {
        pages_ = java.util.Collections.emptyList();
      } else {
        pages_ = null;
        pagesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      ranklistType_ = 0;
      title_ = "";
      ranklistExtra_ = "";
      entranceExtra_ = "";
      schema_ = "";
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.caesar.crawler.live.douyin.codec.protobuf.Douyin.internal_static_RanklistHourEntrance_Detail_descriptor;
    }

    @Override
    public org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Detail getDefaultInstanceForType() {
      return org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Detail.getDefaultInstance();
    }

    @Override
    public org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Detail build() {
      org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Detail result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Detail buildPartial() {
      org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Detail result = new org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Detail(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Detail result) {
      if (pagesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          pages_ = java.util.Collections.unmodifiableList(pages_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.pages_ = pages_;
      } else {
        result.pages_ = pagesBuilder_.build();
      }
    }

    private void buildPartial0(org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Detail result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.ranklistType_ = ranklistType_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.title_ = title_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.ranklistExtra_ = ranklistExtra_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.entranceExtra_ = entranceExtra_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.schema_ = schema_;
      }
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Detail) {
        return mergeFrom((org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Detail)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Detail other) {
      if (other == org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Detail.getDefaultInstance()) return this;
      if (pagesBuilder_ == null) {
        if (!other.pages_.isEmpty()) {
          if (pages_.isEmpty()) {
            pages_ = other.pages_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePagesIsMutable();
            pages_.addAll(other.pages_);
          }
          onChanged();
        }
      } else {
        if (!other.pages_.isEmpty()) {
          if (pagesBuilder_.isEmpty()) {
            pagesBuilder_.dispose();
            pagesBuilder_ = null;
            pages_ = other.pages_;
            bitField0_ = (bitField0_ & ~0x00000001);
            pagesBuilder_ =
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPagesFieldBuilder() : null;
          } else {
            pagesBuilder_.addAllMessages(other.pages_);
          }
        }
      }
      if (other.getRanklistType() != 0) {
        setRanklistType(other.getRanklistType());
      }
      if (!other.getTitle().isEmpty()) {
        title_ = other.title_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getRanklistExtra().isEmpty()) {
        ranklistExtra_ = other.ranklistExtra_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getEntranceExtra().isEmpty()) {
        entranceExtra_ = other.entranceExtra_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getSchema().isEmpty()) {
        schema_ = other.schema_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page m =
                  input.readMessage(
                      org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page.parser(),
                      extensionRegistry);
              if (pagesBuilder_ == null) {
                ensurePagesIsMutable();
                pages_.add(m);
              } else {
                pagesBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 16: {
              ranklistType_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              title_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              ranklistExtra_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              entranceExtra_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              schema_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page> pages_ =
      java.util.Collections.emptyList();
    private void ensurePagesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        pages_ = new java.util.ArrayList<org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page>(pages_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page, org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page.Builder, org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_PageOrBuilder> pagesBuilder_;

    /**
     * <pre>
     * 假设 pages 是 RanklistHourEntrance_Page 类型
     * </pre>
     *
     * <code>repeated .RanklistHourEntrance_Page pages = 1;</code>
     */
    public java.util.List<org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page> getPagesList() {
      if (pagesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(pages_);
      } else {
        return pagesBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * 假设 pages 是 RanklistHourEntrance_Page 类型
     * </pre>
     *
     * <code>repeated .RanklistHourEntrance_Page pages = 1;</code>
     */
    public int getPagesCount() {
      if (pagesBuilder_ == null) {
        return pages_.size();
      } else {
        return pagesBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * 假设 pages 是 RanklistHourEntrance_Page 类型
     * </pre>
     *
     * <code>repeated .RanklistHourEntrance_Page pages = 1;</code>
     */
    public org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page getPages(int index) {
      if (pagesBuilder_ == null) {
        return pages_.get(index);
      } else {
        return pagesBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * 假设 pages 是 RanklistHourEntrance_Page 类型
     * </pre>
     *
     * <code>repeated .RanklistHourEntrance_Page pages = 1;</code>
     */
    public Builder setPages(
        int index, org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page value) {
      if (pagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePagesIsMutable();
        pages_.set(index, value);
        onChanged();
      } else {
        pagesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 假设 pages 是 RanklistHourEntrance_Page 类型
     * </pre>
     *
     * <code>repeated .RanklistHourEntrance_Page pages = 1;</code>
     */
    public Builder setPages(
        int index, org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page.Builder builderForValue) {
      if (pagesBuilder_ == null) {
        ensurePagesIsMutable();
        pages_.set(index, builderForValue.build());
        onChanged();
      } else {
        pagesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 假设 pages 是 RanklistHourEntrance_Page 类型
     * </pre>
     *
     * <code>repeated .RanklistHourEntrance_Page pages = 1;</code>
     */
    public Builder addPages(org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page value) {
      if (pagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePagesIsMutable();
        pages_.add(value);
        onChanged();
      } else {
        pagesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * 假设 pages 是 RanklistHourEntrance_Page 类型
     * </pre>
     *
     * <code>repeated .RanklistHourEntrance_Page pages = 1;</code>
     */
    public Builder addPages(
        int index, org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page value) {
      if (pagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePagesIsMutable();
        pages_.add(index, value);
        onChanged();
      } else {
        pagesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 假设 pages 是 RanklistHourEntrance_Page 类型
     * </pre>
     *
     * <code>repeated .RanklistHourEntrance_Page pages = 1;</code>
     */
    public Builder addPages(
        org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page.Builder builderForValue) {
      if (pagesBuilder_ == null) {
        ensurePagesIsMutable();
        pages_.add(builderForValue.build());
        onChanged();
      } else {
        pagesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 假设 pages 是 RanklistHourEntrance_Page 类型
     * </pre>
     *
     * <code>repeated .RanklistHourEntrance_Page pages = 1;</code>
     */
    public Builder addPages(
        int index, org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page.Builder builderForValue) {
      if (pagesBuilder_ == null) {
        ensurePagesIsMutable();
        pages_.add(index, builderForValue.build());
        onChanged();
      } else {
        pagesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 假设 pages 是 RanklistHourEntrance_Page 类型
     * </pre>
     *
     * <code>repeated .RanklistHourEntrance_Page pages = 1;</code>
     */
    public Builder addAllPages(
        Iterable<? extends org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page> values) {
      if (pagesBuilder_ == null) {
        ensurePagesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, pages_);
        onChanged();
      } else {
        pagesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * 假设 pages 是 RanklistHourEntrance_Page 类型
     * </pre>
     *
     * <code>repeated .RanklistHourEntrance_Page pages = 1;</code>
     */
    public Builder clearPages() {
      if (pagesBuilder_ == null) {
        pages_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        pagesBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 假设 pages 是 RanklistHourEntrance_Page 类型
     * </pre>
     *
     * <code>repeated .RanklistHourEntrance_Page pages = 1;</code>
     */
    public Builder removePages(int index) {
      if (pagesBuilder_ == null) {
        ensurePagesIsMutable();
        pages_.remove(index);
        onChanged();
      } else {
        pagesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * 假设 pages 是 RanklistHourEntrance_Page 类型
     * </pre>
     *
     * <code>repeated .RanklistHourEntrance_Page pages = 1;</code>
     */
    public org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page.Builder getPagesBuilder(
        int index) {
      return getPagesFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * 假设 pages 是 RanklistHourEntrance_Page 类型
     * </pre>
     *
     * <code>repeated .RanklistHourEntrance_Page pages = 1;</code>
     */
    public org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_PageOrBuilder getPagesOrBuilder(
        int index) {
      if (pagesBuilder_ == null) {
        return pages_.get(index);  } else {
        return pagesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * 假设 pages 是 RanklistHourEntrance_Page 类型
     * </pre>
     *
     * <code>repeated .RanklistHourEntrance_Page pages = 1;</code>
     */
    public java.util.List<? extends org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_PageOrBuilder>
         getPagesOrBuilderList() {
      if (pagesBuilder_ != null) {
        return pagesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(pages_);
      }
    }
    /**
     * <pre>
     * 假设 pages 是 RanklistHourEntrance_Page 类型
     * </pre>
     *
     * <code>repeated .RanklistHourEntrance_Page pages = 1;</code>
     */
    public org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page.Builder addPagesBuilder() {
      return getPagesFieldBuilder().addBuilder(
          org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page.getDefaultInstance());
    }
    /**
     * <pre>
     * 假设 pages 是 RanklistHourEntrance_Page 类型
     * </pre>
     *
     * <code>repeated .RanklistHourEntrance_Page pages = 1;</code>
     */
    public org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page.Builder addPagesBuilder(
        int index) {
      return getPagesFieldBuilder().addBuilder(
          index, org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page.getDefaultInstance());
    }
    /**
     * <pre>
     * 假设 pages 是 RanklistHourEntrance_Page 类型
     * </pre>
     *
     * <code>repeated .RanklistHourEntrance_Page pages = 1;</code>
     */
    public java.util.List<org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page.Builder>
         getPagesBuilderList() {
      return getPagesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page, org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page.Builder, org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_PageOrBuilder>
        getPagesFieldBuilder() {
      if (pagesBuilder_ == null) {
        pagesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page, org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page.Builder, org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_PageOrBuilder>(
                pages_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        pages_ = null;
      }
      return pagesBuilder_;
    }

    private int ranklistType_ ;
    /**
     * <pre>
     * 排名列表类型
     * </pre>
     *
     * <code>int32 ranklist_type = 2;</code>
     * @return The ranklistType.
     */
    @Override
    public int getRanklistType() {
      return ranklistType_;
    }
    /**
     * <pre>
     * 排名列表类型
     * </pre>
     *
     * <code>int32 ranklist_type = 2;</code>
     * @param value The ranklistType to set.
     * @return This builder for chaining.
     */
    public Builder setRanklistType(int value) {

      ranklistType_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 排名列表类型
     * </pre>
     *
     * <code>int32 ranklist_type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRanklistType() {
      bitField0_ = (bitField0_ & ~0x00000002);
      ranklistType_ = 0;
      onChanged();
      return this;
    }

    private Object title_ = "";
    /**
     * <pre>
     * 标题
     * </pre>
     *
     * <code>string title = 3;</code>
     * @return The title.
     */
    public String getTitle() {
      Object ref = title_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        title_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 标题
     * </pre>
     *
     * <code>string title = 3;</code>
     * @return The bytes for title.
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 标题
     * </pre>
     *
     * <code>string title = 3;</code>
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      title_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 标题
     * </pre>
     *
     * <code>string title = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      title_ = getDefaultInstance().getTitle();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 标题
     * </pre>
     *
     * <code>string title = 3;</code>
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      title_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private Object ranklistExtra_ = "";
    /**
     * <pre>
     * 排名列表额外信息
     * </pre>
     *
     * <code>string ranklist_extra = 4;</code>
     * @return The ranklistExtra.
     */
    public String getRanklistExtra() {
      Object ref = ranklistExtra_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        ranklistExtra_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 排名列表额外信息
     * </pre>
     *
     * <code>string ranklist_extra = 4;</code>
     * @return The bytes for ranklistExtra.
     */
    public com.google.protobuf.ByteString
        getRanklistExtraBytes() {
      Object ref = ranklistExtra_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        ranklistExtra_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 排名列表额外信息
     * </pre>
     *
     * <code>string ranklist_extra = 4;</code>
     * @param value The ranklistExtra to set.
     * @return This builder for chaining.
     */
    public Builder setRanklistExtra(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      ranklistExtra_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 排名列表额外信息
     * </pre>
     *
     * <code>string ranklist_extra = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearRanklistExtra() {
      ranklistExtra_ = getDefaultInstance().getRanklistExtra();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 排名列表额外信息
     * </pre>
     *
     * <code>string ranklist_extra = 4;</code>
     * @param value The bytes for ranklistExtra to set.
     * @return This builder for chaining.
     */
    public Builder setRanklistExtraBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ranklistExtra_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private Object entranceExtra_ = "";
    /**
     * <pre>
     * 入口额外信息
     * </pre>
     *
     * <code>string entrance_extra = 5;</code>
     * @return The entranceExtra.
     */
    public String getEntranceExtra() {
      Object ref = entranceExtra_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        entranceExtra_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 入口额外信息
     * </pre>
     *
     * <code>string entrance_extra = 5;</code>
     * @return The bytes for entranceExtra.
     */
    public com.google.protobuf.ByteString
        getEntranceExtraBytes() {
      Object ref = entranceExtra_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        entranceExtra_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 入口额外信息
     * </pre>
     *
     * <code>string entrance_extra = 5;</code>
     * @param value The entranceExtra to set.
     * @return This builder for chaining.
     */
    public Builder setEntranceExtra(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      entranceExtra_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 入口额外信息
     * </pre>
     *
     * <code>string entrance_extra = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearEntranceExtra() {
      entranceExtra_ = getDefaultInstance().getEntranceExtra();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 入口额外信息
     * </pre>
     *
     * <code>string entrance_extra = 5;</code>
     * @param value The bytes for entranceExtra to set.
     * @return This builder for chaining.
     */
    public Builder setEntranceExtraBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      entranceExtra_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private Object schema_ = "";
    /**
     * <pre>
     * 模式
     * </pre>
     *
     * <code>string schema = 6;</code>
     * @return The schema.
     */
    public String getSchema() {
      Object ref = schema_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        schema_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 模式
     * </pre>
     *
     * <code>string schema = 6;</code>
     * @return The bytes for schema.
     */
    public com.google.protobuf.ByteString
        getSchemaBytes() {
      Object ref = schema_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        schema_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 模式
     * </pre>
     *
     * <code>string schema = 6;</code>
     * @param value The schema to set.
     * @return This builder for chaining.
     */
    public Builder setSchema(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      schema_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 模式
     * </pre>
     *
     * <code>string schema = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearSchema() {
      schema_ = getDefaultInstance().getSchema();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 模式
     * </pre>
     *
     * <code>string schema = 6;</code>
     * @param value The bytes for schema to set.
     * @return This builder for chaining.
     */
    public Builder setSchemaBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      schema_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:RanklistHourEntrance_Detail)
  }

  // @@protoc_insertion_point(class_scope:RanklistHourEntrance_Detail)
  private static final org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Detail DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Detail();
  }

  public static org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Detail getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RanklistHourEntrance_Detail>
      PARSER = new com.google.protobuf.AbstractParser<RanklistHourEntrance_Detail>() {
    @Override
    public RanklistHourEntrance_Detail parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RanklistHourEntrance_Detail> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<RanklistHourEntrance_Detail> getParserForType() {
    return PARSER;
  }

  @Override
  public org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Detail getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

