// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

// Protobuf Java Version: 3.25.5
package org.caesar.crawler.live.douyin.codec.protobuf;

public interface RanklistHourEntranceMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RanklistHourEntranceMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Common common = 1;</code>
   * @return Whether the common field is set.
   */
  boolean hasCommon();
  /**
   * <code>.Common common = 1;</code>
   * @return The common.
   */
  org.caesar.crawler.live.douyin.codec.protobuf.Common getCommon();
  /**
   * <code>.Common common = 1;</code>
   */
  org.caesar.crawler.live.douyin.codec.protobuf.CommonOrBuilder getCommonOrBuilder();

  /**
   * <code>.RanklistHourEntrance info = 2;</code>
   * @return Whether the info field is set.
   */
  boolean hasInfo();
  /**
   * <code>.RanklistHourEntrance info = 2;</code>
   * @return The info.
   */
  org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance getInfo();
  /**
   * <code>.RanklistHourEntrance info = 2;</code>
   */
  org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntranceOrBuilder getInfoOrBuilder();
}
