// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

// Protobuf Java Version: 3.25.5
package org.caesar.crawler.live.douyin.codec.protobuf;

/**
 * Protobuf type {@code RanklistHourEntrance_Page}
 */
public final class RanklistHourEntrance_Page extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:RanklistHourEntrance_Page)
    RanklistHourEntrance_PageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RanklistHourEntrance_Page.newBuilder() to construct.
  private RanklistHourEntrance_Page(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RanklistHourEntrance_Page() {
    content_ = "";
    backgroundColor_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new RanklistHourEntrance_Page();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.caesar.crawler.live.douyin.codec.protobuf.Douyin.internal_static_RanklistHourEntrance_Page_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.caesar.crawler.live.douyin.codec.protobuf.Douyin.internal_static_RanklistHourEntrance_Page_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page.class, org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page.Builder.class);
  }

  public static final int CONTENT_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile Object content_ = "";
  /**
   * <pre>
   * Content of the page
   * </pre>
   *
   * <code>string content = 1;</code>
   * @return The content.
   */
  @Override
  public String getContent() {
    Object ref = content_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      content_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Content of the page
   * </pre>
   *
   * <code>string content = 1;</code>
   * @return The bytes for content.
   */
  @Override
  public com.google.protobuf.ByteString
      getContentBytes() {
    Object ref = content_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      content_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BACKGROUND_COLOR_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile Object backgroundColor_ = "";
  /**
   * <pre>
   * Background color of the page
   * </pre>
   *
   * <code>string background_color = 2;</code>
   * @return The backgroundColor.
   */
  @Override
  public String getBackgroundColor() {
    Object ref = backgroundColor_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      backgroundColor_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Background color of the page
   * </pre>
   *
   * <code>string background_color = 2;</code>
   * @return The bytes for backgroundColor.
   */
  @Override
  public com.google.protobuf.ByteString
      getBackgroundColorBytes() {
    Object ref = backgroundColor_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      backgroundColor_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SHOW_TIMES_FIELD_NUMBER = 3;
  private long showTimes_ = 0L;
  /**
   * <pre>
   * Number of times the page is shown (or similar)
   * </pre>
   *
   * <code>int64 show_times = 3;</code>
   * @return The showTimes.
   */
  @Override
  public long getShowTimes() {
    return showTimes_;
  }

  public static final int CONTENT_TYPE_FIELD_NUMBER = 4;
  private int contentType_ = 0;
  /**
   * <pre>
   * Type of the content
   * </pre>
   *
   * <code>int32 content_type = 4;</code>
   * @return The contentType.
   */
  @Override
  public int getContentType() {
    return contentType_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, content_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(backgroundColor_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, backgroundColor_);
    }
    if (showTimes_ != 0L) {
      output.writeInt64(3, showTimes_);
    }
    if (contentType_ != 0) {
      output.writeInt32(4, contentType_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, content_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(backgroundColor_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, backgroundColor_);
    }
    if (showTimes_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, showTimes_);
    }
    if (contentType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, contentType_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page)) {
      return super.equals(obj);
    }
    org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page other = (org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page) obj;

    if (!getContent()
        .equals(other.getContent())) return false;
    if (!getBackgroundColor()
        .equals(other.getBackgroundColor())) return false;
    if (getShowTimes()
        != other.getShowTimes()) return false;
    if (getContentType()
        != other.getContentType()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getContent().hashCode();
    hash = (37 * hash) + BACKGROUND_COLOR_FIELD_NUMBER;
    hash = (53 * hash) + getBackgroundColor().hashCode();
    hash = (37 * hash) + SHOW_TIMES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getShowTimes());
    hash = (37 * hash) + CONTENT_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getContentType();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code RanklistHourEntrance_Page}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:RanklistHourEntrance_Page)
      org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_PageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.caesar.crawler.live.douyin.codec.protobuf.Douyin.internal_static_RanklistHourEntrance_Page_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.caesar.crawler.live.douyin.codec.protobuf.Douyin.internal_static_RanklistHourEntrance_Page_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page.class, org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page.Builder.class);
    }

    // Construct using org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      content_ = "";
      backgroundColor_ = "";
      showTimes_ = 0L;
      contentType_ = 0;
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.caesar.crawler.live.douyin.codec.protobuf.Douyin.internal_static_RanklistHourEntrance_Page_descriptor;
    }

    @Override
    public org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page getDefaultInstanceForType() {
      return org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page.getDefaultInstance();
    }

    @Override
    public org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page build() {
      org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page buildPartial() {
      org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page result = new org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.content_ = content_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.backgroundColor_ = backgroundColor_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.showTimes_ = showTimes_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.contentType_ = contentType_;
      }
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page) {
        return mergeFrom((org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page other) {
      if (other == org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page.getDefaultInstance()) return this;
      if (!other.getContent().isEmpty()) {
        content_ = other.content_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getBackgroundColor().isEmpty()) {
        backgroundColor_ = other.backgroundColor_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getShowTimes() != 0L) {
        setShowTimes(other.getShowTimes());
      }
      if (other.getContentType() != 0) {
        setContentType(other.getContentType());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              content_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              backgroundColor_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              showTimes_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              contentType_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private Object content_ = "";
    /**
     * <pre>
     * Content of the page
     * </pre>
     *
     * <code>string content = 1;</code>
     * @return The content.
     */
    public String getContent() {
      Object ref = content_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        content_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * Content of the page
     * </pre>
     *
     * <code>string content = 1;</code>
     * @return The bytes for content.
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Content of the page
     * </pre>
     *
     * <code>string content = 1;</code>
     * @param value The content to set.
     * @return This builder for chaining.
     */
    public Builder setContent(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      content_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Content of the page
     * </pre>
     *
     * <code>string content = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearContent() {
      content_ = getDefaultInstance().getContent();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Content of the page
     * </pre>
     *
     * <code>string content = 1;</code>
     * @param value The bytes for content to set.
     * @return This builder for chaining.
     */
    public Builder setContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      content_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private Object backgroundColor_ = "";
    /**
     * <pre>
     * Background color of the page
     * </pre>
     *
     * <code>string background_color = 2;</code>
     * @return The backgroundColor.
     */
    public String getBackgroundColor() {
      Object ref = backgroundColor_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        backgroundColor_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * Background color of the page
     * </pre>
     *
     * <code>string background_color = 2;</code>
     * @return The bytes for backgroundColor.
     */
    public com.google.protobuf.ByteString
        getBackgroundColorBytes() {
      Object ref = backgroundColor_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        backgroundColor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Background color of the page
     * </pre>
     *
     * <code>string background_color = 2;</code>
     * @param value The backgroundColor to set.
     * @return This builder for chaining.
     */
    public Builder setBackgroundColor(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      backgroundColor_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Background color of the page
     * </pre>
     *
     * <code>string background_color = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearBackgroundColor() {
      backgroundColor_ = getDefaultInstance().getBackgroundColor();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Background color of the page
     * </pre>
     *
     * <code>string background_color = 2;</code>
     * @param value The bytes for backgroundColor to set.
     * @return This builder for chaining.
     */
    public Builder setBackgroundColorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      backgroundColor_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private long showTimes_ ;
    /**
     * <pre>
     * Number of times the page is shown (or similar)
     * </pre>
     *
     * <code>int64 show_times = 3;</code>
     * @return The showTimes.
     */
    @Override
    public long getShowTimes() {
      return showTimes_;
    }
    /**
     * <pre>
     * Number of times the page is shown (or similar)
     * </pre>
     *
     * <code>int64 show_times = 3;</code>
     * @param value The showTimes to set.
     * @return This builder for chaining.
     */
    public Builder setShowTimes(long value) {

      showTimes_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Number of times the page is shown (or similar)
     * </pre>
     *
     * <code>int64 show_times = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearShowTimes() {
      bitField0_ = (bitField0_ & ~0x00000004);
      showTimes_ = 0L;
      onChanged();
      return this;
    }

    private int contentType_ ;
    /**
     * <pre>
     * Type of the content
     * </pre>
     *
     * <code>int32 content_type = 4;</code>
     * @return The contentType.
     */
    @Override
    public int getContentType() {
      return contentType_;
    }
    /**
     * <pre>
     * Type of the content
     * </pre>
     *
     * <code>int32 content_type = 4;</code>
     * @param value The contentType to set.
     * @return This builder for chaining.
     */
    public Builder setContentType(int value) {

      contentType_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Type of the content
     * </pre>
     *
     * <code>int32 content_type = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearContentType() {
      bitField0_ = (bitField0_ & ~0x00000008);
      contentType_ = 0;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:RanklistHourEntrance_Page)
  }

  // @@protoc_insertion_point(class_scope:RanklistHourEntrance_Page)
  private static final org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page();
  }

  public static org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RanklistHourEntrance_Page>
      PARSER = new com.google.protobuf.AbstractParser<RanklistHourEntrance_Page>() {
    @Override
    public RanklistHourEntrance_Page parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RanklistHourEntrance_Page> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<RanklistHourEntrance_Page> getParserForType() {
    return PARSER;
  }

  @Override
  public org.caesar.crawler.live.douyin.codec.protobuf.RanklistHourEntrance_Page getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

