// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

// Protobuf Java Version: 3.25.5
package org.caesar.crawler.live.douyin.codec.protobuf;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Message messagesList = 1;</code>
   */
  java.util.List<org.caesar.crawler.live.douyin.codec.protobuf.Message>
      getMessagesListList();
  /**
   * <code>repeated .Message messagesList = 1;</code>
   */
  org.caesar.crawler.live.douyin.codec.protobuf.Message getMessagesList(int index);
  /**
   * <code>repeated .Message messagesList = 1;</code>
   */
  int getMessagesListCount();
  /**
   * <code>repeated .Message messagesList = 1;</code>
   */
  java.util.List<? extends org.caesar.crawler.live.douyin.codec.protobuf.MessageOrBuilder>
      getMessagesListOrBuilderList();
  /**
   * <code>repeated .Message messagesList = 1;</code>
   */
  org.caesar.crawler.live.douyin.codec.protobuf.MessageOrBuilder getMessagesListOrBuilder(
      int index);

  /**
   * <code>string cursor = 2;</code>
   * @return The cursor.
   */
  String getCursor();
  /**
   * <code>string cursor = 2;</code>
   * @return The bytes for cursor.
   */
  com.google.protobuf.ByteString
      getCursorBytes();

  /**
   * <code>uint64 fetchInterval = 3;</code>
   * @return The fetchInterval.
   */
  long getFetchInterval();

  /**
   * <code>uint64 now = 4;</code>
   * @return The now.
   */
  long getNow();

  /**
   * <code>string internalExt = 5;</code>
   * @return The internalExt.
   */
  String getInternalExt();
  /**
   * <code>string internalExt = 5;</code>
   * @return The bytes for internalExt.
   */
  com.google.protobuf.ByteString
      getInternalExtBytes();

  /**
   * <code>uint32 fetchType = 6;</code>
   * @return The fetchType.
   */
  int getFetchType();

  /**
   * <code>map&lt;string, string&gt; routeParams = 7;</code>
   */
  int getRouteParamsCount();
  /**
   * <code>map&lt;string, string&gt; routeParams = 7;</code>
   */
  boolean containsRouteParams(
      String key);
  /**
   * Use {@link #getRouteParamsMap()} instead.
   */
  @Deprecated
  java.util.Map<String, String>
  getRouteParams();
  /**
   * <code>map&lt;string, string&gt; routeParams = 7;</code>
   */
  java.util.Map<String, String>
  getRouteParamsMap();
  /**
   * <code>map&lt;string, string&gt; routeParams = 7;</code>
   */
  /* nullable */
String getRouteParamsOrDefault(
      String key,
      /* nullable */
String defaultValue);
  /**
   * <code>map&lt;string, string&gt; routeParams = 7;</code>
   */
  String getRouteParamsOrThrow(
      String key);

  /**
   * <code>uint64 heartbeatDuration = 8;</code>
   * @return The heartbeatDuration.
   */
  long getHeartbeatDuration();

  /**
   * <code>bool needAck = 9;</code>
   * @return The needAck.
   */
  boolean getNeedAck();

  /**
   * <code>string pushServer = 10;</code>
   * @return The pushServer.
   */
  String getPushServer();
  /**
   * <code>string pushServer = 10;</code>
   * @return The bytes for pushServer.
   */
  com.google.protobuf.ByteString
      getPushServerBytes();

  /**
   * <code>string liveCursor = 11;</code>
   * @return The liveCursor.
   */
  String getLiveCursor();
  /**
   * <code>string liveCursor = 11;</code>
   * @return The bytes for liveCursor.
   */
  com.google.protobuf.ByteString
      getLiveCursorBytes();

  /**
   * <code>bool historyNoMore = 12;</code>
   * @return The historyNoMore.
   */
  boolean getHistoryNoMore();
}
