// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

// Protobuf Java Version: 3.25.5
package org.caesar.crawler.live.douyin.codec.protobuf;

public interface RspOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Rsp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 a = 1;</code>
   * @return The a.
   */
  int getA();

  /**
   * <code>int32 b = 2;</code>
   * @return The b.
   */
  int getB();

  /**
   * <code>int32 c = 3;</code>
   * @return The c.
   */
  int getC();

  /**
   * <code>string d = 4;</code>
   * @return The d.
   */
  String getD();
  /**
   * <code>string d = 4;</code>
   * @return The bytes for d.
   */
  com.google.protobuf.ByteString
      getDBytes();

  /**
   * <code>int32 e = 5;</code>
   * @return The e.
   */
  int getE();

  /**
   * <code>.Rsp.F f = 6;</code>
   * @return Whether the f field is set.
   */
  boolean hasF();
  /**
   * <code>.Rsp.F f = 6;</code>
   * @return The f.
   */
  org.caesar.crawler.live.douyin.codec.protobuf.Rsp.F getF();
  /**
   * <code>.Rsp.F f = 6;</code>
   */
  org.caesar.crawler.live.douyin.codec.protobuf.Rsp.FOrBuilder getFOrBuilder();

  /**
   * <code>string g = 7;</code>
   * @return The g.
   */
  String getG();
  /**
   * <code>string g = 7;</code>
   * @return The bytes for g.
   */
  com.google.protobuf.ByteString
      getGBytes();

  /**
   * <code>uint64 h = 10;</code>
   * @return The h.
   */
  long getH();

  /**
   * <code>uint64 i = 11;</code>
   * @return The i.
   */
  long getI();

  /**
   * <code>uint64 j = 13;</code>
   * @return The j.
   */
  long getJ();
}
