// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

// Protobuf Java Version: 3.25.5
package org.caesar.crawler.live.douyin.codec.protobuf;

public interface SocialMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SocialMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Common common = 1;</code>
   * @return Whether the common field is set.
   */
  boolean hasCommon();
  /**
   * <code>.Common common = 1;</code>
   * @return The common.
   */
  org.caesar.crawler.live.douyin.codec.protobuf.Common getCommon();
  /**
   * <code>.Common common = 1;</code>
   */
  org.caesar.crawler.live.douyin.codec.protobuf.CommonOrBuilder getCommonOrBuilder();

  /**
   * <code>.User user = 2;</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <code>.User user = 2;</code>
   * @return The user.
   */
  org.caesar.crawler.live.douyin.codec.protobuf.User getUser();
  /**
   * <code>.User user = 2;</code>
   */
  org.caesar.crawler.live.douyin.codec.protobuf.UserOrBuilder getUserOrBuilder();

  /**
   * <code>uint64 shareType = 3;</code>
   * @return The shareType.
   */
  long getShareType();

  /**
   * <code>uint64 action = 4;</code>
   * @return The action.
   */
  long getAction();

  /**
   * <code>string shareTarget = 5;</code>
   * @return The shareTarget.
   */
  String getShareTarget();
  /**
   * <code>string shareTarget = 5;</code>
   * @return The bytes for shareTarget.
   */
  com.google.protobuf.ByteString
      getShareTargetBytes();

  /**
   * <code>uint64 followCount = 6;</code>
   * @return The followCount.
   */
  long getFollowCount();

  /**
   * <code>.PublicAreaCommon publicAreaCommon = 7;</code>
   * @return Whether the publicAreaCommon field is set.
   */
  boolean hasPublicAreaCommon();
  /**
   * <code>.PublicAreaCommon publicAreaCommon = 7;</code>
   * @return The publicAreaCommon.
   */
  org.caesar.crawler.live.douyin.codec.protobuf.PublicAreaCommon getPublicAreaCommon();
  /**
   * <code>.PublicAreaCommon publicAreaCommon = 7;</code>
   */
  org.caesar.crawler.live.douyin.codec.protobuf.PublicAreaCommonOrBuilder getPublicAreaCommonOrBuilder();
}
