// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

// Protobuf Java Version: 3.25.5
package org.caesar.crawler.live.douyin.codec.protobuf;

/**
 * Protobuf type {@code TextPieceGift}
 */
public final class TextPieceGift extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:TextPieceGift)
    TextPieceGiftOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TextPieceGift.newBuilder() to construct.
  private TextPieceGift(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TextPieceGift() {
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new TextPieceGift();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.caesar.crawler.live.douyin.codec.protobuf.Douyin.internal_static_TextPieceGift_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.caesar.crawler.live.douyin.codec.protobuf.Douyin.internal_static_TextPieceGift_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.caesar.crawler.live.douyin.codec.protobuf.TextPieceGift.class, org.caesar.crawler.live.douyin.codec.protobuf.TextPieceGift.Builder.class);
  }

  private int bitField0_;
  public static final int GIFTID_FIELD_NUMBER = 1;
  private long giftId_ = 0L;
  /**
   * <code>uint64 giftId = 1;</code>
   * @return The giftId.
   */
  @Override
  public long getGiftId() {
    return giftId_;
  }

  public static final int NAMEREF_FIELD_NUMBER = 2;
  private org.caesar.crawler.live.douyin.codec.protobuf.PatternRef nameRef_;
  /**
   * <code>.PatternRef nameRef = 2;</code>
   * @return Whether the nameRef field is set.
   */
  @Override
  public boolean hasNameRef() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.PatternRef nameRef = 2;</code>
   * @return The nameRef.
   */
  @Override
  public org.caesar.crawler.live.douyin.codec.protobuf.PatternRef getNameRef() {
    return nameRef_ == null ? org.caesar.crawler.live.douyin.codec.protobuf.PatternRef.getDefaultInstance() : nameRef_;
  }
  /**
   * <code>.PatternRef nameRef = 2;</code>
   */
  @Override
  public org.caesar.crawler.live.douyin.codec.protobuf.PatternRefOrBuilder getNameRefOrBuilder() {
    return nameRef_ == null ? org.caesar.crawler.live.douyin.codec.protobuf.PatternRef.getDefaultInstance() : nameRef_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (giftId_ != 0L) {
      output.writeUInt64(1, giftId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getNameRef());
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (giftId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, giftId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getNameRef());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.caesar.crawler.live.douyin.codec.protobuf.TextPieceGift)) {
      return super.equals(obj);
    }
    org.caesar.crawler.live.douyin.codec.protobuf.TextPieceGift other = (org.caesar.crawler.live.douyin.codec.protobuf.TextPieceGift) obj;

    if (getGiftId()
        != other.getGiftId()) return false;
    if (hasNameRef() != other.hasNameRef()) return false;
    if (hasNameRef()) {
      if (!getNameRef()
          .equals(other.getNameRef())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + GIFTID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getGiftId());
    if (hasNameRef()) {
      hash = (37 * hash) + NAMEREF_FIELD_NUMBER;
      hash = (53 * hash) + getNameRef().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.caesar.crawler.live.douyin.codec.protobuf.TextPieceGift parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.caesar.crawler.live.douyin.codec.protobuf.TextPieceGift parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.caesar.crawler.live.douyin.codec.protobuf.TextPieceGift parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.caesar.crawler.live.douyin.codec.protobuf.TextPieceGift parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.caesar.crawler.live.douyin.codec.protobuf.TextPieceGift parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.caesar.crawler.live.douyin.codec.protobuf.TextPieceGift parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.caesar.crawler.live.douyin.codec.protobuf.TextPieceGift parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.caesar.crawler.live.douyin.codec.protobuf.TextPieceGift parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.caesar.crawler.live.douyin.codec.protobuf.TextPieceGift parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.caesar.crawler.live.douyin.codec.protobuf.TextPieceGift parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.caesar.crawler.live.douyin.codec.protobuf.TextPieceGift parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.caesar.crawler.live.douyin.codec.protobuf.TextPieceGift parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.caesar.crawler.live.douyin.codec.protobuf.TextPieceGift prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code TextPieceGift}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:TextPieceGift)
      org.caesar.crawler.live.douyin.codec.protobuf.TextPieceGiftOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.caesar.crawler.live.douyin.codec.protobuf.Douyin.internal_static_TextPieceGift_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.caesar.crawler.live.douyin.codec.protobuf.Douyin.internal_static_TextPieceGift_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.caesar.crawler.live.douyin.codec.protobuf.TextPieceGift.class, org.caesar.crawler.live.douyin.codec.protobuf.TextPieceGift.Builder.class);
    }

    // Construct using org.caesar.crawler.live.douyin.codec.protobuf.TextPieceGift.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getNameRefFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      giftId_ = 0L;
      nameRef_ = null;
      if (nameRefBuilder_ != null) {
        nameRefBuilder_.dispose();
        nameRefBuilder_ = null;
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.caesar.crawler.live.douyin.codec.protobuf.Douyin.internal_static_TextPieceGift_descriptor;
    }

    @Override
    public org.caesar.crawler.live.douyin.codec.protobuf.TextPieceGift getDefaultInstanceForType() {
      return org.caesar.crawler.live.douyin.codec.protobuf.TextPieceGift.getDefaultInstance();
    }

    @Override
    public org.caesar.crawler.live.douyin.codec.protobuf.TextPieceGift build() {
      org.caesar.crawler.live.douyin.codec.protobuf.TextPieceGift result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public org.caesar.crawler.live.douyin.codec.protobuf.TextPieceGift buildPartial() {
      org.caesar.crawler.live.douyin.codec.protobuf.TextPieceGift result = new org.caesar.crawler.live.douyin.codec.protobuf.TextPieceGift(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.caesar.crawler.live.douyin.codec.protobuf.TextPieceGift result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.giftId_ = giftId_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.nameRef_ = nameRefBuilder_ == null
            ? nameRef_
            : nameRefBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.caesar.crawler.live.douyin.codec.protobuf.TextPieceGift) {
        return mergeFrom((org.caesar.crawler.live.douyin.codec.protobuf.TextPieceGift)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.caesar.crawler.live.douyin.codec.protobuf.TextPieceGift other) {
      if (other == org.caesar.crawler.live.douyin.codec.protobuf.TextPieceGift.getDefaultInstance()) return this;
      if (other.getGiftId() != 0L) {
        setGiftId(other.getGiftId());
      }
      if (other.hasNameRef()) {
        mergeNameRef(other.getNameRef());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              giftId_ = input.readUInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  getNameRefFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long giftId_ ;
    /**
     * <code>uint64 giftId = 1;</code>
     * @return The giftId.
     */
    @Override
    public long getGiftId() {
      return giftId_;
    }
    /**
     * <code>uint64 giftId = 1;</code>
     * @param value The giftId to set.
     * @return This builder for chaining.
     */
    public Builder setGiftId(long value) {

      giftId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 giftId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearGiftId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      giftId_ = 0L;
      onChanged();
      return this;
    }

    private org.caesar.crawler.live.douyin.codec.protobuf.PatternRef nameRef_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.caesar.crawler.live.douyin.codec.protobuf.PatternRef, org.caesar.crawler.live.douyin.codec.protobuf.PatternRef.Builder, org.caesar.crawler.live.douyin.codec.protobuf.PatternRefOrBuilder> nameRefBuilder_;
    /**
     * <code>.PatternRef nameRef = 2;</code>
     * @return Whether the nameRef field is set.
     */
    public boolean hasNameRef() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.PatternRef nameRef = 2;</code>
     * @return The nameRef.
     */
    public org.caesar.crawler.live.douyin.codec.protobuf.PatternRef getNameRef() {
      if (nameRefBuilder_ == null) {
        return nameRef_ == null ? org.caesar.crawler.live.douyin.codec.protobuf.PatternRef.getDefaultInstance() : nameRef_;
      } else {
        return nameRefBuilder_.getMessage();
      }
    }
    /**
     * <code>.PatternRef nameRef = 2;</code>
     */
    public Builder setNameRef(org.caesar.crawler.live.douyin.codec.protobuf.PatternRef value) {
      if (nameRefBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        nameRef_ = value;
      } else {
        nameRefBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.PatternRef nameRef = 2;</code>
     */
    public Builder setNameRef(
        org.caesar.crawler.live.douyin.codec.protobuf.PatternRef.Builder builderForValue) {
      if (nameRefBuilder_ == null) {
        nameRef_ = builderForValue.build();
      } else {
        nameRefBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.PatternRef nameRef = 2;</code>
     */
    public Builder mergeNameRef(org.caesar.crawler.live.douyin.codec.protobuf.PatternRef value) {
      if (nameRefBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          nameRef_ != null &&
          nameRef_ != org.caesar.crawler.live.douyin.codec.protobuf.PatternRef.getDefaultInstance()) {
          getNameRefBuilder().mergeFrom(value);
        } else {
          nameRef_ = value;
        }
      } else {
        nameRefBuilder_.mergeFrom(value);
      }
      if (nameRef_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.PatternRef nameRef = 2;</code>
     */
    public Builder clearNameRef() {
      bitField0_ = (bitField0_ & ~0x00000002);
      nameRef_ = null;
      if (nameRefBuilder_ != null) {
        nameRefBuilder_.dispose();
        nameRefBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.PatternRef nameRef = 2;</code>
     */
    public org.caesar.crawler.live.douyin.codec.protobuf.PatternRef.Builder getNameRefBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getNameRefFieldBuilder().getBuilder();
    }
    /**
     * <code>.PatternRef nameRef = 2;</code>
     */
    public org.caesar.crawler.live.douyin.codec.protobuf.PatternRefOrBuilder getNameRefOrBuilder() {
      if (nameRefBuilder_ != null) {
        return nameRefBuilder_.getMessageOrBuilder();
      } else {
        return nameRef_ == null ?
            org.caesar.crawler.live.douyin.codec.protobuf.PatternRef.getDefaultInstance() : nameRef_;
      }
    }
    /**
     * <code>.PatternRef nameRef = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.caesar.crawler.live.douyin.codec.protobuf.PatternRef, org.caesar.crawler.live.douyin.codec.protobuf.PatternRef.Builder, org.caesar.crawler.live.douyin.codec.protobuf.PatternRefOrBuilder>
        getNameRefFieldBuilder() {
      if (nameRefBuilder_ == null) {
        nameRefBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.caesar.crawler.live.douyin.codec.protobuf.PatternRef, org.caesar.crawler.live.douyin.codec.protobuf.PatternRef.Builder, org.caesar.crawler.live.douyin.codec.protobuf.PatternRefOrBuilder>(
                getNameRef(),
                getParentForChildren(),
                isClean());
        nameRef_ = null;
      }
      return nameRefBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:TextPieceGift)
  }

  // @@protoc_insertion_point(class_scope:TextPieceGift)
  private static final org.caesar.crawler.live.douyin.codec.protobuf.TextPieceGift DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.caesar.crawler.live.douyin.codec.protobuf.TextPieceGift();
  }

  public static org.caesar.crawler.live.douyin.codec.protobuf.TextPieceGift getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TextPieceGift>
      PARSER = new com.google.protobuf.AbstractParser<TextPieceGift>() {
    @Override
    public TextPieceGift parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TextPieceGift> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<TextPieceGift> getParserForType() {
    return PARSER;
  }

  @Override
  public org.caesar.crawler.live.douyin.codec.protobuf.TextPieceGift getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

