// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

// Protobuf Java Version: 3.25.5
package org.caesar.crawler.live.douyin.codec.protobuf;

public interface TextPieceGiftOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TextPieceGift)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 giftId = 1;</code>
   * @return The giftId.
   */
  long getGiftId();

  /**
   * <code>.PatternRef nameRef = 2;</code>
   * @return Whether the nameRef field is set.
   */
  boolean hasNameRef();
  /**
   * <code>.PatternRef nameRef = 2;</code>
   * @return The nameRef.
   */
  org.caesar.crawler.live.douyin.codec.protobuf.PatternRef getNameRef();
  /**
   * <code>.PatternRef nameRef = 2;</code>
   */
  org.caesar.crawler.live.douyin.codec.protobuf.PatternRefOrBuilder getNameRefOrBuilder();
}
