// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

// Protobuf Java Version: 3.25.5
package org.caesar.crawler.live.douyin.codec.protobuf;

public interface TextOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Text)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string key = 1;</code>
   * @return The key.
   */
  String getKey();
  /**
   * <code>string key = 1;</code>
   * @return The bytes for key.
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>string default_pattern = 2;</code>
   * @return The defaultPattern.
   */
  String getDefaultPattern();
  /**
   * <code>string default_pattern = 2;</code>
   * @return The bytes for defaultPattern.
   */
  com.google.protobuf.ByteString
      getDefaultPatternBytes();

  /**
   * <code>.TextFormat default_format = 3;</code>
   * @return Whether the defaultFormat field is set.
   */
  boolean hasDefaultFormat();
  /**
   * <code>.TextFormat default_format = 3;</code>
   * @return The defaultFormat.
   */
  org.caesar.crawler.live.douyin.codec.protobuf.TextFormat getDefaultFormat();
  /**
   * <code>.TextFormat default_format = 3;</code>
   */
  org.caesar.crawler.live.douyin.codec.protobuf.TextFormatOrBuilder getDefaultFormatOrBuilder();

  /**
   * <code>repeated .TextPiece pieces = 4;</code>
   */
  java.util.List<org.caesar.crawler.live.douyin.codec.protobuf.TextPiece>
      getPiecesList();
  /**
   * <code>repeated .TextPiece pieces = 4;</code>
   */
  org.caesar.crawler.live.douyin.codec.protobuf.TextPiece getPieces(int index);
  /**
   * <code>repeated .TextPiece pieces = 4;</code>
   */
  int getPiecesCount();
  /**
   * <code>repeated .TextPiece pieces = 4;</code>
   */
  java.util.List<? extends org.caesar.crawler.live.douyin.codec.protobuf.TextPieceOrBuilder>
      getPiecesOrBuilderList();
  /**
   * <code>repeated .TextPiece pieces = 4;</code>
   */
  org.caesar.crawler.live.douyin.codec.protobuf.TextPieceOrBuilder getPiecesOrBuilder(
      int index);
}
